# Generated by build_srams.sh from l1d/l1d_tag_array_config.py
word_size = 11
num_words = 32
num_rw_ports = 0
num_r_ports = 1
num_w_ports = 1
output_path = "/media/nisitha/My_Passport/MOODLE/OpenRAM_Project/OpenRAM_Memory_Design/cache/sram_sky130/l1d_tag_array"
output_name = "l1d_tag_array"

tech_name = "sky130"
nominal_corner_only = True
analytical_delay = True
check_lvsdrc = True
# Call magic/netgen directly; we already run inside the Nix devShell
use_nix = False
route_supplies = "ring"
uniquify = True
