# Generated by build_srams.sh from l2/l2_tag_array_config.py
word_size = 20
num_words = 32
num_rw_ports = 0
num_r_ports = 1
num_w_ports = 1
output_path = "/media/nisitha/My_Passport/MOODLE/OpenRAM_Project/OpenRAM_Memory_Design/cache/sram/l2_tag_array"
output_name = "l2_tag_array"

tech_name = "scn4m_subm"
nominal_corner_only = True
analytical_delay = True
check_lvsdrc = True
# Call magic/netgen directly; we already run inside the Nix devShell
use_nix = False
# With the default words_per_row = 1, OpenRAM's router left one write driver's
# w_en input unconnected (LVS mismatch). Two words per row changes the column
# layout and gives a clean macro (DRC 0, LVS match).
words_per_row = 2
