/* Generated by Amaranth Yosys 0.35 (PyPI ver 0.35.0.0.post81, git sha1 cc31c6ebc) */




module l1i(main_addr, main_dout, main_stall, clk, rst, csb, addr, dout, stall, main_csb);
  reg \$auto$verilog_backend.cc:2189:dump_module$5  = 0;
  wire \$1 ;
  wire \$10 ;
  wire \$100 ;
  wire \$102 ;
  wire \$104 ;
  wire \$106 ;
  wire \$12 ;
  wire \$14 ;
  wire \$16 ;
  wire \$18 ;
  wire \$20 ;
  wire \$22 ;
  wire \$24 ;
  wire \$26 ;
  wire \$28 ;
  wire \$3 ;
  wire \$30 ;
  wire \$32 ;
  wire \$34 ;
  wire \$36 ;
  wire \$38 ;
  wire \$40 ;
  wire \$42 ;
  wire \$44 ;
  wire [31:0] \$46 ;
  wire [2:0] \$47 ;
  wire [8:0] \$49 ;
  wire \$5 ;
  wire \$52 ;
  wire [31:0] \$54 ;
  wire [2:0] \$55 ;
  wire [8:0] \$57 ;
  wire \$60 ;
  wire \$62 ;
  wire \$64 ;
  wire \$66 ;
  wire \$68 ;
  wire [5:0] \$7 ;
  wire \$70 ;
  wire \$72 ;
  wire \$74 ;
  wire \$76 ;
  wire \$78 ;
  wire [5:0] \$8 ;
  wire \$80 ;
  wire \$82 ;
  wire \$84 ;
  wire \$86 ;
  wire \$88 ;
  wire \$90 ;
  wire \$92 ;
  wire \$94 ;
  wire \$96 ;
  wire \$98 ;
  input [15:0] addr;
  wire [15:0] addr;
  input clk;
  wire clk;
  input csb;
  wire csb;
  reg [4:0] data_read_addr0;
  reg data_read_csb0;
  wire [127:0] data_read_dout0;
  reg [4:0] data_write_addr0;
  reg data_write_csb0;
  reg [127:0] data_write_din0;
  output [31:0] dout;
  reg [31:0] dout;
  output [13:0] main_addr;
  reg [13:0] main_addr;
  output main_csb;
  reg main_csb;
  input [127:0] main_dout;
  wire [127:0] main_dout;
  input main_stall;
  wire main_stall;
  reg [1:0] offset = 2'h0;
  reg [1:0] offset_next;
  input rst;
  wire rst;
  reg [4:0] set = 5'h00;
  reg [4:0] set_next;
  output stall;
  reg stall;
  reg [3:0] state = 4'h0;
  reg [3:0] state_next;
  reg [8:0] tag = 9'h000;
  reg [8:0] tag_next;
  reg [4:0] tag_read_addr0;
  reg tag_read_csb0;
  wire [9:0] tag_read_dout0;
  reg [4:0] tag_write_addr0;
  reg tag_write_csb0;
  reg [9:0] tag_write_din0;
  assign \$100  = tag_read_dout0[9] &  \$98 ;
  assign \$102  = ~  main_stall;
  assign \$104  = ~  main_stall;
  assign \$106  = ~  main_stall;
  assign \$10  = tag_read_dout0[8:0] ==  tag;
  assign \$12  = tag_read_dout0[9] &  \$10 ;
  assign \$14  = ~  main_stall;
  assign \$16  = tag_read_dout0[8:0] ==  tag;
  assign \$18  = tag_read_dout0[9] &  \$16 ;
  assign \$1  = tag_read_dout0[8:0] ==  tag;
  assign \$20  = ~  main_stall;
  assign \$22  = set ==  5'h1f;
  assign \$24  = ~  csb;
  assign \$26  = tag_read_dout0[8:0] ==  tag;
  assign \$28  = tag_read_dout0[9] &  \$26 ;
  assign \$30  = ~  main_stall;
  assign \$32  = ~  main_stall;
  assign \$34  = set ==  addr[6:2];
  assign \$36  = tag_read_dout0[8:0] ==  tag;
  assign \$38  = tag_read_dout0[9] &  \$36 ;
  assign \$3  = tag_read_dout0[9] &  \$1 ;
  assign \$40  = ~  main_stall;
  assign \$42  = tag_read_dout0[8:0] ==  tag;
  assign \$44  = tag_read_dout0[9] &  \$42 ;
  assign \$47  = 1'h0 +  offset;
  assign \$49  = \$47  *  6'h20;
  assign \$46  = data_read_dout0 >> \$49 ;
  assign \$52  = ~  main_stall;
  assign \$55  = 1'h0 +  offset;
  assign \$57  = \$55  *  6'h20;
  assign \$54  = main_dout >> \$57 ;
  assign \$5  = ~  main_stall;
  assign \$60  = ~  main_stall;
  assign \$62  = ~  main_stall;
  assign \$64  = ~  main_stall;
  assign \$66  = ~  main_stall;
  assign \$68  = ~  main_stall;
  assign \$70  = ~  main_stall;
  assign \$72  = tag_read_dout0[8:0] ==  tag;
  assign \$74  = tag_read_dout0[9] &  \$72 ;
  assign \$76  = ~  main_stall;
  assign \$78  = tag_read_dout0[8:0] ==  tag;
  assign \$80  = tag_read_dout0[9] &  \$78 ;
  assign \$82  = ~  main_stall;
  assign \$84  = tag_read_dout0[8:0] ==  tag;
  assign \$86  = tag_read_dout0[9] &  \$84 ;
  assign \$88  = ~  main_stall;
  assign \$8  = set +  1'h1;
  assign \$90  = tag_read_dout0[8:0] ==  tag;
  assign \$92  = tag_read_dout0[9] &  \$90 ;
  assign \$94  = ~  main_stall;
  assign \$96  = ~  main_stall;
  assign \$98  = tag_read_dout0[8:0] ==  tag;
  always @(posedge clk)
    state <= state_next;
  always @(posedge clk)
    offset <= offset_next;
  always @(posedge clk)
    set <= set_next;
  always @(posedge clk)
    tag <= tag_next;
  l1i_tag_array \U$$0  (
    .addr0(tag_write_addr0),
    .addr1(tag_read_addr0),
    .clk0(clk),
    .clk1(clk),
    .csb0(tag_write_csb0),
    .csb1(tag_read_csb0),
    .din0(tag_write_din0),
    .dout1(tag_read_dout0)
  );
  sram_128x32_1r1w \U$$1  (
    .addr0(data_write_addr0),
    .addr1(data_read_addr0),
    .clk0(clk),
    .clk1(clk),
    .csb0(data_write_csb0),
    .csb1(data_read_csb0),
    .din0(data_write_din0),
    .dout1(data_read_dout0)
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$5 ) begin end
    tag_write_csb0 = 1'h1;
    casez (state)
      4'h0:
          tag_write_csb0 = 1'h0;
      4'h2:
          ;
      4'h3:
          ;
      4'h6:
          ;
      4'h7:
          casez (\$60 )
            1'h1:
                tag_write_csb0 = 1'h0;
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$5 ) begin end
    tag_write_addr0 = 5'h00;
    casez (state)
      4'h0:
          tag_write_addr0 = set;
      4'h2:
          ;
      4'h3:
          ;
      4'h6:
          ;
      4'h7:
          casez (\$62 )
            1'h1:
                tag_write_addr0 = set;
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$5 ) begin end
    tag_write_din0 = 10'h000;
    casez (state)
      4'h0:
          tag_write_din0 = 10'h000;
      4'h2:
          ;
      4'h3:
          ;
      4'h6:
          ;
      4'h7:
          casez (\$64 )
            1'h1:
                tag_write_din0 = { 1'h1, tag };
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$5 ) begin end
    data_write_csb0 = 1'h1;
    casez (state)
      4'h0:
          data_write_csb0 = 1'h0;
      4'h2:
          ;
      4'h3:
          ;
      4'h6:
          ;
      4'h7:
          casez (\$66 )
            1'h1:
                data_write_csb0 = 1'h0;
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$5 ) begin end
    data_write_addr0 = 5'h00;
    casez (state)
      4'h0:
          data_write_addr0 = set;
      4'h2:
          ;
      4'h3:
          ;
      4'h6:
          ;
      4'h7:
          casez (\$68 )
            1'h1:
                data_write_addr0 = set;
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$5 ) begin end
    data_write_din0 = 128'h00000000000000000000000000000000;
    casez (state)
      4'h0:
          data_write_din0 = 128'h00000000000000000000000000000000;
      4'h2:
          ;
      4'h3:
          ;
      4'h6:
          ;
      4'h7:
          casez (\$70 )
            1'h1:
                data_write_din0 = main_dout;
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$5 ) begin end
    tag_read_csb0 = 1'h0;
    casez (state)
      4'h0:
          ;
      4'h2:
          tag_read_csb0 = 1'h0;
      4'h3:
        begin
          tag_read_csb0 = 1'h0;
          casez (\$74 )
            1'h1:
                tag_read_csb0 = 1'h0;
          endcase
        end
      4'h6:
          tag_read_csb0 = 1'h0;
      4'h7:
        begin
          tag_read_csb0 = 1'h0;
          casez (\$76 )
            1'h1:
                tag_read_csb0 = 1'h0;
          endcase
        end
      4'h9:
          tag_read_csb0 = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$5 ) begin end
    tag_read_addr0 = 5'h00;
    casez (state)
      4'h0:
          ;
      4'h2:
          tag_read_addr0 = addr[6:2];
      4'h3:
        begin
          tag_read_addr0 = set;
          casez (\$80 )
            1'h1:
                tag_read_addr0 = addr[6:2];
          endcase
        end
      4'h6:
          tag_read_addr0 = set;
      4'h7:
        begin
          tag_read_addr0 = set;
          casez (\$82 )
            1'h1:
                tag_read_addr0 = addr[6:2];
          endcase
        end
      4'h9:
          tag_read_addr0 = set;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$5 ) begin end
    data_read_csb0 = 1'h0;
    casez (state)
      4'h0:
          ;
      4'h2:
          data_read_csb0 = 1'h0;
      4'h3:
        begin
          data_read_csb0 = 1'h0;
          casez (\$86 )
            1'h1:
                data_read_csb0 = 1'h0;
          endcase
        end
      4'h6:
          data_read_csb0 = 1'h0;
      4'h7:
        begin
          data_read_csb0 = 1'h0;
          casez (\$88 )
            1'h1:
                data_read_csb0 = 1'h0;
          endcase
        end
      4'h9:
          data_read_csb0 = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$5 ) begin end
    data_read_addr0 = 5'h00;
    casez (state)
      4'h0:
          ;
      4'h2:
          data_read_addr0 = addr[6:2];
      4'h3:
        begin
          data_read_addr0 = set;
          casez (\$92 )
            1'h1:
                data_read_addr0 = addr[6:2];
          endcase
        end
      4'h6:
          data_read_addr0 = set;
      4'h7:
        begin
          data_read_addr0 = set;
          casez (\$94 )
            1'h1:
                data_read_addr0 = addr[6:2];
          endcase
        end
      4'h9:
          data_read_addr0 = set;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$5 ) begin end
    main_csb = 1'h1;
    casez (state)
      4'h0:
          ;
      4'h2:
          ;
      4'h3:
        begin
          casez (\$96 )
            1'h1:
                main_csb = 1'h0;
          endcase
          casez (\$100 )
            1'h1:
                main_csb = 1'h1;
          endcase
        end
      4'h6:
          casez (\$102 )
            1'h1:
                main_csb = 1'h0;
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$5 ) begin end
    main_addr = 14'h0000;
    casez (state)
      4'h0:
          ;
      4'h2:
          ;
      4'h3:
          casez (\$104 )
            1'h1:
                main_addr = { tag, set };
          endcase
      4'h6:
          casez (\$106 )
            1'h1:
                main_addr = { tag, set };
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$5 ) begin end
    tag_next = tag;
    casez (state)
      4'h0:
          ;
      4'h2:
          tag_next = addr[15:7];
      4'h3:
          casez (\$3 )
            1'h1:
                tag_next = addr[15:7];
          endcase
      4'h7:
          casez (\$5 )
            1'h1:
                tag_next = addr[15:7];
          endcase
    endcase
    casez (rst)
      1'h1:
          tag_next = 9'h000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$5 ) begin end
    set_next = set;
    casez (state)
      4'h0:
          set_next = \$8 [4:0];
      4'h2:
          set_next = addr[6:2];
      4'h3:
          casez (\$12 )
            1'h1:
                set_next = addr[6:2];
          endcase
      4'h7:
          casez (\$14 )
            1'h1:
                set_next = addr[6:2];
          endcase
    endcase
    casez (rst)
      1'h1:
          set_next = 5'h00;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$5 ) begin end
    offset_next = offset;
    casez (state)
      4'h0:
          ;
      4'h2:
          offset_next = addr[1:0];
      4'h3:
          casez (\$18 )
            1'h1:
                offset_next = addr[1:0];
          endcase
      4'h7:
          casez (\$20 )
            1'h1:
                offset_next = addr[1:0];
          endcase
    endcase
    casez (rst)
      1'h1:
          offset_next = 2'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$5 ) begin end
    state_next = state;
    casez (state)
      4'h0:
          casez (\$22 )
            1'h1:
                state_next = 4'h2;
          endcase
      4'h2:
          casez (\$24 )
            1'h1:
                state_next = 4'h3;
          endcase
      4'h3:
        begin
          casez (main_stall)
            1'h1:
                state_next = 4'h6;
            default:
                state_next = 4'h7;
          endcase
          casez (\$28 )
            1'h1:
                casez (csb)
                  1'h1:
                      state_next = 4'h2;
                  default:
                      state_next = 4'h3;
                endcase
          endcase
        end
      4'h6:
          casez (\$30 )
            1'h1:
                state_next = 4'h7;
          endcase
      4'h7:
          casez (\$32 )
            1'h1:
                casez (csb)
                  1'h1:
                      state_next = 4'h2;
                  default:
                      casez (\$34 )
                        1'h1:
                            state_next = 4'h9;
                        default:
                            state_next = 4'h3;
                      endcase
                endcase
          endcase
      4'h9:
          state_next = 4'h3;
    endcase
    casez (rst)
      1'h1:
          state_next = 4'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$5 ) begin end
    stall = 1'h1;
    casez (state)
      4'h2:
          stall = 1'h0;
      4'h3:
          casez (\$38 )
            1'h1:
                stall = 1'h0;
          endcase
      4'h7:
          casez (\$40 )
            1'h1:
                stall = 1'h0;
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$5 ) begin end
    dout = 32'd0;
    casez (state)
      4'h2:
          ;
      4'h3:
          casez (\$44 )
            1'h1:
                dout = \$46 ;
          endcase
      4'h7:
          casez (\$52 )
            1'h1:
                dout = \$54 ;
          endcase
    endcase
  end
  assign \$7  = \$8 ;
endmodule
