/* Generated by Amaranth Yosys 0.35 (PyPI ver 0.35.0.0.post81, git sha1 cc31c6ebc) */




module l2(main_web, main_addr, main_din, main_dout, main_stall, clk, rst, flush, csb, web, addr, din, dout, stall, main_csb);
  reg \$auto$verilog_backend.cc:2189:dump_module$8  = 0;
  wire \$1 ;
  wire \$101 ;
  wire \$103 ;
  wire \$105 ;
  wire \$107 ;
  wire \$109 ;
  wire [5:0] \$11 ;
  wire \$111 ;
  wire \$113 ;
  wire \$115 ;
  wire \$117 ;
  wire \$119 ;
  wire [5:0] \$12 ;
  wire \$121 ;
  wire \$123 ;
  wire \$125 ;
  wire \$127 ;
  wire \$129 ;
  wire \$130 ;
  wire [4:0] \$131 ;
  wire [5:0] \$133 ;
  wire \$137 ;
  wire \$139 ;
  wire \$14 ;
  wire [1:0] \$141 ;
  wire [1:0] \$142 ;
  wire \$144 ;
  wire \$146 ;
  wire \$148 ;
  wire \$15 ;
  wire \$150 ;
  wire \$152 ;
  wire \$154 ;
  wire \$156 ;
  wire \$158 ;
  wire [4:0] \$16 ;
  wire \$160 ;
  wire \$162 ;
  wire \$164 ;
  wire \$166 ;
  wire \$168 ;
  wire \$170 ;
  wire \$172 ;
  wire [127:0] \$174 ;
  wire [1:0] \$175 ;
  wire [9:0] \$177 ;
  wire [5:0] \$18 ;
  wire \$180 ;
  wire \$182 ;
  wire [127:0] \$184 ;
  wire [1:0] \$185 ;
  wire [9:0] \$187 ;
  wire \$190 ;
  wire [127:0] \$192 ;
  wire [1:0] \$193 ;
  wire [9:0] \$195 ;
  wire \$198 ;
  wire \$200 ;
  wire \$202 ;
  wire \$204 ;
  wire \$206 ;
  wire \$208 ;
  wire \$210 ;
  wire \$212 ;
  wire \$214 ;
  wire \$216 ;
  wire \$218 ;
  wire \$22 ;
  wire \$220 ;
  wire \$222 ;
  wire \$224 ;
  wire \$226 ;
  wire \$228 ;
  wire \$230 ;
  wire \$232 ;
  wire \$234 ;
  wire \$236 ;
  wire \$238 ;
  wire \$24 ;
  wire \$240 ;
  wire \$242 ;
  wire \$244 ;
  wire \$246 ;
  wire \$248 ;
  wire \$250 ;
  wire \$252 ;
  wire \$254 ;
  wire \$256 ;
  wire \$258 ;
  wire \$26 ;
  wire \$260 ;
  wire \$262 ;
  wire \$264 ;
  wire \$266 ;
  wire \$268 ;
  wire \$270 ;
  wire \$272 ;
  wire \$274 ;
  wire \$276 ;
  wire \$278 ;
  wire \$28 ;
  wire \$280 ;
  wire \$282 ;
  wire \$284 ;
  wire \$286 ;
  wire \$288 ;
  wire \$290 ;
  wire \$292 ;
  wire \$294 ;
  wire \$296 ;
  wire \$298 ;
  wire \$3 ;
  wire [5:0] \$30 ;
  wire \$300 ;
  wire \$302 ;
  wire \$304 ;
  wire \$306 ;
  wire \$308 ;
  wire [5:0] \$31 ;
  wire \$310 ;
  wire \$312 ;
  wire \$314 ;
  wire \$316 ;
  wire \$318 ;
  wire \$320 ;
  wire \$322 ;
  wire \$324 ;
  wire \$326 ;
  wire \$328 ;
  wire \$33 ;
  wire \$330 ;
  wire \$332 ;
  wire \$334 ;
  wire \$336 ;
  wire \$338 ;
  wire \$340 ;
  wire [5:0] \$342 ;
  wire [5:0] \$343 ;
  wire \$345 ;
  wire \$347 ;
  wire \$349 ;
  wire \$35 ;
  wire \$351 ;
  wire \$353 ;
  wire \$355 ;
  wire \$357 ;
  wire \$359 ;
  wire \$361 ;
  wire \$363 ;
  wire \$365 ;
  wire \$367 ;
  wire \$369 ;
  wire \$37 ;
  wire \$371 ;
  wire \$373 ;
  wire \$375 ;
  wire [5:0] \$377 ;
  wire [5:0] \$378 ;
  wire \$380 ;
  wire \$382 ;
  wire \$384 ;
  wire \$386 ;
  wire \$388 ;
  wire \$39 ;
  wire \$390 ;
  wire \$392 ;
  wire \$394 ;
  wire \$396 ;
  wire \$398 ;
  wire \$400 ;
  wire \$402 ;
  wire \$404 ;
  wire \$406 ;
  wire \$408 ;
  wire \$41 ;
  wire \$410 ;
  wire [5:0] \$412 ;
  wire [5:0] \$413 ;
  wire \$415 ;
  wire \$417 ;
  wire \$419 ;
  wire \$421 ;
  wire \$423 ;
  wire \$425 ;
  wire \$427 ;
  wire \$429 ;
  wire \$43 ;
  wire \$431 ;
  wire \$433 ;
  wire \$435 ;
  wire \$437 ;
  wire \$439 ;
  wire \$441 ;
  wire \$443 ;
  wire \$445 ;
  wire \$447 ;
  wire \$449 ;
  wire \$45 ;
  wire \$451 ;
  wire \$453 ;
  wire \$455 ;
  wire \$457 ;
  wire \$459 ;
  wire \$461 ;
  wire \$463 ;
  wire \$465 ;
  wire \$467 ;
  wire \$469 ;
  wire \$47 ;
  wire \$471 ;
  wire \$473 ;
  wire \$475 ;
  wire \$477 ;
  wire \$479 ;
  wire \$481 ;
  wire \$483 ;
  wire \$485 ;
  wire \$487 ;
  wire \$489 ;
  wire \$49 ;
  wire \$491 ;
  wire \$493 ;
  wire \$495 ;
  wire \$497 ;
  wire \$499 ;
  wire \$5 ;
  wire \$501 ;
  wire [7:0] \$503 ;
  wire [4:0] \$504 ;
  wire [7:0] \$507 ;
  wire [4:0] \$508 ;
  wire \$51 ;
  wire \$511 ;
  wire \$513 ;
  wire \$515 ;
  wire \$517 ;
  wire \$519 ;
  wire \$521 ;
  wire \$523 ;
  wire \$525 ;
  wire \$527 ;
  wire \$529 ;
  wire \$53 ;
  wire \$531 ;
  wire \$533 ;
  wire \$535 ;
  wire \$537 ;
  wire \$539 ;
  wire \$541 ;
  wire \$543 ;
  wire \$545 ;
  wire \$547 ;
  wire \$549 ;
  wire \$55 ;
  wire \$551 ;
  wire \$553 ;
  wire \$555 ;
  wire [1:0] \$557 ;
  wire \$558 ;
  wire [1:0] \$560 ;
  wire [1:0] \$562 ;
  wire \$563 ;
  wire [1:0] \$565 ;
  wire \$567 ;
  wire \$569 ;
  wire \$57 ;
  wire [1:0] \$571 ;
  wire \$572 ;
  wire [1:0] \$574 ;
  wire [1:0] \$576 ;
  wire \$577 ;
  wire [1:0] \$579 ;
  wire \$581 ;
  wire [1:0] \$583 ;
  wire \$584 ;
  wire \$586 ;
  wire [1:0] \$588 ;
  wire \$59 ;
  wire [1:0] \$590 ;
  wire \$591 ;
  wire \$593 ;
  wire [1:0] \$595 ;
  wire \$597 ;
  wire \$599 ;
  wire \$601 ;
  wire \$603 ;
  wire \$605 ;
  wire \$607 ;
  wire \$609 ;
  wire \$61 ;
  wire \$611 ;
  wire \$613 ;
  wire \$615 ;
  wire \$63 ;
  wire \$65 ;
  wire \$67 ;
  wire \$69 ;
  wire \$7 ;
  wire \$71 ;
  wire \$73 ;
  wire \$75 ;
  wire \$76 ;
  wire [4:0] \$77 ;
  wire [5:0] \$79 ;
  wire \$83 ;
  wire \$85 ;
  wire \$87 ;
  wire \$89 ;
  wire \$9 ;
  wire \$91 ;
  wire \$93 ;
  wire \$95 ;
  wire \$97 ;
  wire \$99 ;
  input [13:0] addr;
  wire [13:0] addr;
  input clk;
  wire clk;
  input csb;
  wire csb;
  reg [4:0] data_read_addr0;
  reg [4:0] data_read_addr1;
  reg data_read_csb0;
  reg data_read_csb1;
  wire [255:0] data_read_dout0;
  wire [255:0] data_read_dout1;
  reg [4:0] data_write_addr0;
  reg [4:0] data_write_addr1;
  reg data_write_csb0;
  reg data_write_csb1;
  reg [255:0] data_write_din0;
  reg [255:0] data_write_din1;
  input [127:0] din;
  wire [127:0] din;
  reg [127:0] din_reg = 128'h00000000000000000000000000000000;
  reg [127:0] din_reg_next;
  output [127:0] dout;
  reg [127:0] dout;
  input flush;
  wire flush;
  output [12:0] main_addr;
  reg [12:0] main_addr;
  output main_csb;
  reg main_csb;
  output [255:0] main_din;
  reg [255:0] main_din;
  input [255:0] main_dout;
  wire [255:0] main_dout;
  input main_stall;
  wire main_stall;
  output main_web;
  reg main_web;
  reg offset = 1'h0;
  reg offset_next;
  input rst;
  wire rst;
  reg [4:0] set = 5'h00;
  reg [4:0] set_next;
  output stall;
  reg stall;
  reg [3:0] state = 4'h0;
  reg [3:0] state_next;
  reg [7:0] tag = 8'h00;
  reg [7:0] tag_next;
  reg [4:0] tag_read_addr0;
  reg tag_read_csb0;
  wire [19:0] tag_read_dout0;
  reg [4:0] tag_write_addr0;
  reg tag_write_csb0;
  reg [19:0] tag_write_din0;
  reg [4:0] use_read_addr0;
  reg use_read_csb0;
  wire [1:0] use_read_dout0;
  reg [4:0] use_write_addr0;
  reg use_write_csb0;
  reg [1:0] use_write_din0;
  reg way = 1'h0;
  reg way_next;
  input web;
  wire web;
  reg web_reg = 1'h0;
  reg web_reg_next;
  assign \$9  = ~  main_stall;
  assign \$99  = tag_read_dout0[9] &  tag_read_dout0[8];
  assign \$101  = ~  use_read_dout0[1];
  assign \$103  = tag_read_dout0[19] &  tag_read_dout0[18];
  assign \$105  = tag_read_dout0[7:0] ==  tag;
  assign \$107  = tag_read_dout0[9] &  \$105 ;
  assign \$109  = set ==  addr[5:1];
  assign \$111  = tag_read_dout0[17:10] ==  tag;
  assign \$113  = tag_read_dout0[19] &  \$111 ;
  assign \$115  = set ==  addr[5:1];
  assign \$117  = ~  main_stall;
  assign \$119  = ~  main_stall;
  assign \$121  = set ==  addr[5:1];
  assign \$123  = ~  main_stall;
  assign \$125  = ~  main_stall;
  assign \$127  = |  set;
  assign \$12  = set +  1'h1;
  assign \$131  = way *  4'ha;
  assign \$133  = \$131  +  4'h8;
  assign \$130  = tag_read_dout0 >> \$133 ;
  assign \$129  = ~  \$130 ;
  assign \$137  = ~  main_stall;
  assign \$139  = \$129  |  \$137 ;
  assign \$142  = way +  1'h1;
  assign \$144  = ~  use_read_dout0[0];
  assign \$146  = tag_read_dout0[9] &  tag_read_dout0[8];
  assign \$148  = ~  use_read_dout0[1];
  assign \$150  = tag_read_dout0[19] &  tag_read_dout0[18];
  assign \$152  = tag_read_dout0[7:0] ==  tag;
  assign \$154  = tag_read_dout0[9] &  \$152 ;
  assign \$156  = tag_read_dout0[17:10] ==  tag;
  assign \$158  = tag_read_dout0[19] &  \$156 ;
  assign \$160  = tag_read_dout0[7:0] ==  tag;
  assign \$162  = tag_read_dout0[9] &  \$160 ;
  assign \$164  = tag_read_dout0[17:10] ==  tag;
  assign \$166  = tag_read_dout0[19] &  \$164 ;
  assign \$168  = ~  main_stall;
  assign \$16  = way *  4'ha;
  assign \$170  = tag_read_dout0[7:0] ==  tag;
  assign \$172  = tag_read_dout0[9] &  \$170 ;
  assign \$175  = 1'h0 +  offset;
  assign \$177  = \$175  *  8'h80;
  assign \$174  = data_read_dout0 >> \$177 ;
  assign \$180  = tag_read_dout0[17:10] ==  tag;
  assign \$182  = tag_read_dout0[19] &  \$180 ;
  assign \$185  = 1'h0 +  offset;
  assign \$187  = \$185  *  8'h80;
  assign \$184  = data_read_dout1 >> \$187 ;
  assign \$18  = \$16  +  4'h8;
  assign \$190  = ~  main_stall;
  assign \$193  = 1'h0 +  offset;
  assign \$195  = \$193  *  8'h80;
  assign \$192  = main_dout >> \$195 ;
  assign \$198  = ~  main_stall;
  assign \$1  = tag_read_dout0[7:0] ==  tag;
  assign \$15  = tag_read_dout0 >> \$18 ;
  assign \$200  = tag_read_dout0[8] &  \$198 ;
  assign \$202  = ~  main_stall;
  assign \$204  = tag_read_dout0[18] &  \$202 ;
  assign \$206  = tag_read_dout0[7:0] ==  tag;
  assign \$208  = tag_read_dout0[9] &  \$206 ;
  assign \$14  = ~  \$15 ;
  assign \$210  = ~  web_reg;
  assign \$212  = tag_read_dout0[17:10] ==  tag;
  assign \$214  = tag_read_dout0[19] &  \$212 ;
  assign \$216  = ~  web_reg;
  assign \$218  = ~  main_stall;
  assign \$220  = ~  main_stall;
  assign \$222  = tag_read_dout0[8] &  \$220 ;
  assign \$224  = ~  main_stall;
  assign \$226  = tag_read_dout0[18] &  \$224 ;
  assign \$228  = tag_read_dout0[7:0] ==  tag;
  assign \$22  = ~  main_stall;
  assign \$230  = tag_read_dout0[9] &  \$228 ;
  assign \$232  = ~  web_reg;
  assign \$234  = tag_read_dout0[17:10] ==  tag;
  assign \$236  = tag_read_dout0[19] &  \$234 ;
  assign \$238  = ~  web_reg;
  assign \$240  = ~  main_stall;
  assign \$242  = ~  main_stall;
  assign \$244  = tag_read_dout0[8] &  \$242 ;
  assign \$246  = ~  main_stall;
  assign \$248  = tag_read_dout0[18] &  \$246 ;
  assign \$24  = \$14  |  \$22 ;
  assign \$250  = tag_read_dout0[7:0] ==  tag;
  assign \$252  = tag_read_dout0[9] &  \$250 ;
  assign \$254  = ~  web_reg;
  assign \$256  = tag_read_dout0[17:10] ==  tag;
  assign \$258  = tag_read_dout0[19] &  \$256 ;
  assign \$260  = ~  web_reg;
  assign \$262  = ~  main_stall;
  assign \$264  = ~  web_reg;
  assign \$266  = ~  web_reg;
  assign \$268  = tag_read_dout0[7:0] ==  tag;
  assign \$270  = tag_read_dout0[9] &  \$268 ;
  assign \$272  = ~  web_reg;
  assign \$274  = ~  main_stall;
  assign \$276  = tag_read_dout0[7:0] ==  tag;
  assign \$278  = tag_read_dout0[9] &  \$276 ;
  assign \$280  = ~  web_reg;
  assign \$282  = ~  main_stall;
  assign \$284  = tag_read_dout0[7:0] ==  tag;
  assign \$286  = tag_read_dout0[9] &  \$284 ;
  assign \$288  = ~  web_reg;
  assign \$28  = \$24  &  \$26 ;
  assign \$290  = ~  main_stall;
  assign \$292  = ~  web_reg;
  assign \$294  = tag_read_dout0[17:10] ==  tag;
  assign \$296  = tag_read_dout0[19] &  \$294 ;
  assign \$298  = ~  web_reg;
  assign \$300  = ~  main_stall;
  assign \$302  = tag_read_dout0[17:10] ==  tag;
  assign \$304  = tag_read_dout0[19] &  \$302 ;
  assign \$306  = ~  web_reg;
  assign \$308  = ~  main_stall;
  assign \$310  = tag_read_dout0[17:10] ==  tag;
  assign \$312  = tag_read_dout0[19] &  \$310 ;
  assign \$314  = ~  web_reg;
  assign \$316  = ~  main_stall;
  assign \$318  = ~  web_reg;
  assign \$31  = set +  1'h1;
  assign \$320  = ~  tag_read_dout0[18];
  assign \$322  = ~  main_stall;
  assign \$324  = \$320  |  \$322 ;
  assign \$326  = tag_read_dout0[7:0] ==  tag;
  assign \$328  = tag_read_dout0[9] &  \$326 ;
  assign \$330  = tag_read_dout0[17:10] ==  tag;
  assign \$332  = tag_read_dout0[19] &  \$330 ;
  assign \$334  = ~  main_stall;
  assign \$336  = ~  tag_read_dout0[18];
  assign \$338  = ~  main_stall;
  assign \$33  = tag_read_dout0[7:0] ==  tag;
  assign \$340  = \$336  |  \$338 ;
  assign \$343  = set +  1'h1;
  assign \$345  = tag_read_dout0[7:0] ==  tag;
  assign \$347  = tag_read_dout0[9] &  \$345 ;
  assign \$349  = tag_read_dout0[17:10] ==  tag;
  assign \$351  = tag_read_dout0[19] &  \$349 ;
  assign \$353  = ~  main_stall;
  assign \$355  = ~  tag_read_dout0[18];
  assign \$357  = ~  main_stall;
  assign \$35  = tag_read_dout0[9] &  \$33 ;
  assign \$359  = \$355  |  \$357 ;
  assign \$361  = tag_read_dout0[7:0] ==  tag;
  assign \$363  = tag_read_dout0[9] &  \$361 ;
  assign \$365  = tag_read_dout0[17:10] ==  tag;
  assign \$367  = tag_read_dout0[19] &  \$365 ;
  assign \$369  = ~  main_stall;
  assign \$371  = ~  tag_read_dout0[18];
  assign \$373  = ~  main_stall;
  assign \$375  = \$371  |  \$373 ;
  assign \$378  = set +  1'h1;
  assign \$37  = tag_read_dout0[17:10] ==  tag;
  assign \$380  = tag_read_dout0[7:0] ==  tag;
  assign \$382  = tag_read_dout0[9] &  \$380 ;
  assign \$384  = tag_read_dout0[17:10] ==  tag;
  assign \$386  = tag_read_dout0[19] &  \$384 ;
  assign \$388  = ~  main_stall;
  assign \$390  = ~  tag_read_dout0[18];
  assign \$392  = ~  main_stall;
  assign \$394  = \$390  |  \$392 ;
  assign \$396  = tag_read_dout0[7:0] ==  tag;
  assign \$398  = tag_read_dout0[9] &  \$396 ;
  assign \$3  = tag_read_dout0[9] &  \$1 ;
  assign \$39  = tag_read_dout0[19] &  \$37 ;
  assign \$400  = tag_read_dout0[17:10] ==  tag;
  assign \$402  = tag_read_dout0[19] &  \$400 ;
  assign \$404  = ~  main_stall;
  assign \$406  = ~  tag_read_dout0[18];
  assign \$408  = ~  main_stall;
  assign \$410  = \$406  |  \$408 ;
  assign \$413  = set +  1'h1;
  assign \$415  = tag_read_dout0[7:0] ==  tag;
  assign \$417  = tag_read_dout0[9] &  \$415 ;
  assign \$41  = ~  main_stall;
  assign \$419  = tag_read_dout0[17:10] ==  tag;
  assign \$421  = tag_read_dout0[19] &  \$419 ;
  assign \$423  = ~  main_stall;
  assign \$425  = ~  main_stall;
  assign \$427  = tag_read_dout0[8] &  \$425 ;
  assign \$429  = ~  main_stall;
  assign \$431  = tag_read_dout0[18] &  \$429 ;
  assign \$433  = ~  main_stall;
  assign \$435  = ~  use_read_dout0[0];
  assign \$437  = tag_read_dout0[9] &  tag_read_dout0[8];
  assign \$43  = tag_read_dout0[7:0] ==  tag;
  assign \$439  = ~  use_read_dout0[1];
  assign \$441  = tag_read_dout0[19] &  tag_read_dout0[18];
  assign \$443  = tag_read_dout0[7:0] ==  tag;
  assign \$445  = tag_read_dout0[9] &  \$443 ;
  assign \$447  = tag_read_dout0[17:10] ==  tag;
  assign \$449  = tag_read_dout0[19] &  \$447 ;
  assign \$451  = ~  main_stall;
  assign \$453  = ~  main_stall;
  assign \$455  = ~  main_stall;
  assign \$457  = ~  main_stall;
  assign \$45  = tag_read_dout0[9] &  \$43 ;
  assign \$459  = tag_read_dout0[8] &  \$457 ;
  assign \$461  = ~  main_stall;
  assign \$463  = tag_read_dout0[18] &  \$461 ;
  assign \$465  = ~  main_stall;
  assign \$467  = ~  use_read_dout0[0];
  assign \$469  = tag_read_dout0[9] &  tag_read_dout0[8];
  assign \$471  = ~  use_read_dout0[1];
  assign \$473  = tag_read_dout0[19] &  tag_read_dout0[18];
  assign \$475  = ~  main_stall;
  assign \$477  = ~  main_stall;
  assign \$47  = tag_read_dout0[17:10] ==  tag;
  assign \$479  = ~  main_stall;
  assign \$481  = ~  main_stall;
  assign \$483  = tag_read_dout0[8] &  \$481 ;
  assign \$485  = ~  main_stall;
  assign \$487  = tag_read_dout0[18] &  \$485 ;
  assign \$489  = ~  main_stall;
  assign \$491  = ~  use_read_dout0[0];
  assign \$493  = tag_read_dout0[9] &  tag_read_dout0[8];
  assign \$495  = ~  use_read_dout0[1];
  assign \$497  = tag_read_dout0[19] &  tag_read_dout0[18];
  assign \$49  = tag_read_dout0[19] &  \$47 ;
  assign \$499  = ~  main_stall;
  assign \$501  = ~  main_stall;
  assign \$504  = way *  4'ha;
  assign \$503  = tag_read_dout0 >> \$504 ;
  assign \$508  = way *  4'ha;
  assign \$507  = tag_read_dout0 >> \$508 ;
  assign \$511  = ~  main_stall;
  assign \$513  = ~  main_stall;
  assign \$515  = tag_read_dout0[8] &  \$513 ;
  assign \$517  = ~  main_stall;
  assign \$51  = ~  main_stall;
  assign \$519  = tag_read_dout0[18] &  \$517 ;
  assign \$521  = ~  main_stall;
  assign \$523  = ~  use_read_dout0[0];
  assign \$525  = tag_read_dout0[9] &  tag_read_dout0[8];
  assign \$527  = ~  use_read_dout0[1];
  assign \$529  = tag_read_dout0[19] &  tag_read_dout0[18];
  assign \$531  = ~  main_stall;
  assign \$533  = tag_read_dout0[7:0] ==  tag;
  assign \$535  = tag_read_dout0[9] &  \$533 ;
  assign \$537  = tag_read_dout0[17:10] ==  tag;
  assign \$53  = tag_read_dout0[7:0] ==  tag;
  assign \$539  = tag_read_dout0[19] &  \$537 ;
  assign \$541  = ~  main_stall;
  assign \$543  = tag_read_dout0[7:0] ==  tag;
  assign \$545  = tag_read_dout0[9] &  \$543 ;
  assign \$547  = tag_read_dout0[17:10] ==  tag;
  assign \$549  = tag_read_dout0[19] &  \$547 ;
  assign \$551  = ~  main_stall;
  assign \$553  = tag_read_dout0[7:0] ==  tag;
  assign \$555  = tag_read_dout0[9] &  \$553 ;
  assign \$558  = use_read_dout0[0] >  use_read_dout0[0];
  assign \$55  = tag_read_dout0[9] &  \$53 ;
  assign \$560  = use_read_dout0[0] -  \$558 ;
  assign \$563  = use_read_dout0[1] >  use_read_dout0[0];
  assign \$565  = use_read_dout0[1] -  \$563 ;
  assign \$567  = tag_read_dout0[17:10] ==  tag;
  assign \$569  = tag_read_dout0[19] &  \$567 ;
  assign \$572  = use_read_dout0[0] >  use_read_dout0[1];
  assign \$574  = use_read_dout0[0] -  \$572 ;
  assign \$577  = use_read_dout0[1] >  use_read_dout0[1];
  assign \$57  = tag_read_dout0[17:10] ==  tag;
  assign \$579  = use_read_dout0[1] -  \$577 ;
  assign \$581  = ~  main_stall;
  assign \$584  = use_read_dout0 >> way;
  assign \$586  = use_read_dout0[0] >  \$584 ;
  assign \$588  = use_read_dout0[0] -  \$586 ;
  assign \$591  = use_read_dout0 >> way;
  assign \$593  = use_read_dout0[1] >  \$591 ;
  assign \$595  = use_read_dout0[1] -  \$593 ;
  assign \$597  = tag_read_dout0[7:0] ==  tag;
  assign \$5  = tag_read_dout0[17:10] ==  tag;
  assign \$59  = tag_read_dout0[19] &  \$57 ;
  assign \$599  = tag_read_dout0[9] &  \$597 ;
  assign \$601  = tag_read_dout0[17:10] ==  tag;
  assign \$603  = tag_read_dout0[19] &  \$601 ;
  assign \$605  = ~  main_stall;
  assign \$607  = tag_read_dout0[7:0] ==  tag;
  assign \$609  = tag_read_dout0[9] &  \$607 ;
  assign \$611  = tag_read_dout0[17:10] ==  tag;
  assign \$613  = tag_read_dout0[19] &  \$611 ;
  assign \$615  = ~  main_stall;
  assign \$61  = ~  main_stall;
  assign \$63  = tag_read_dout0[7:0] ==  tag;
  assign \$65  = tag_read_dout0[9] &  \$63 ;
  assign \$67  = tag_read_dout0[17:10] ==  tag;
  assign \$69  = tag_read_dout0[19] &  \$67 ;
  assign \$71  = ~  main_stall;
  assign \$73  = set ==  5'h1f;
  assign \$77  = way *  4'ha;
  assign \$7  = tag_read_dout0[19] &  \$5 ;
  assign \$79  = \$77  +  4'h8;
  assign \$76  = tag_read_dout0 >> \$79 ;
  assign \$75  = ~  \$76 ;
  assign \$83  = ~  main_stall;
  assign \$85  = \$75  |  \$83 ;
  assign \$89  = \$85  &  \$87 ;
  assign \$91  = set ==  5'h1f;
  assign \$93  = \$89  &  \$91 ;
  assign \$95  = ~  csb;
  assign \$97  = ~  use_read_dout0[0];
  always @(posedge clk)
    way <= way_next;
  always @(posedge clk)
    state <= state_next;
  always @(posedge clk)
    din_reg <= din_reg_next;
  always @(posedge clk)
    web_reg <= web_reg_next;
  always @(posedge clk)
    offset <= offset_next;
  always @(posedge clk)
    set <= set_next;
  always @(posedge clk)
    tag <= tag_next;
  l2_tag_array \U$$0  (
    .addr0(tag_write_addr0),
    .addr1(tag_read_addr0),
    .clk0(clk),
    .clk1(clk),
    .csb0(tag_write_csb0),
    .csb1(tag_read_csb0),
    .din0(tag_write_din0),
    .dout1(tag_read_dout0)
  );
  l2_data_array \U$$1  (
    .addr0(data_write_addr0),
    .addr1(data_read_addr0),
    .clk0(clk),
    .clk1(clk),
    .csb0(data_write_csb0),
    .csb1(data_read_csb0),
    .din0(data_write_din0),
    .dout1(data_read_dout0)
  );
  l2_data_array \U$$2  (
    .addr0(data_write_addr1),
    .addr1(data_read_addr1),
    .clk0(clk),
    .clk1(clk),
    .csb0(data_write_csb1),
    .csb1(data_read_csb1),
    .din0(data_write_din1),
    .dout1(data_read_dout1)
  );
  l2_use_array \U$$3  (
    .addr0(use_write_addr0),
    .addr1(use_read_addr0),
    .clk0(clk),
    .clk1(clk),
    .csb0(use_write_csb0),
    .csb1(use_read_csb0),
    .din0(use_write_din0),
    .dout1(use_read_dout0)
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$8 ) begin end
    web_reg_next = web_reg;
    casez (state)
      4'h0:
          ;
      4'h1:
          ;
      4'h2:
          web_reg_next = web;
      4'h3:
        begin
          casez (\$55 )
            1'h1:
                web_reg_next = web;
          endcase
          casez (\$59 )
            1'h1:
                web_reg_next = web;
          endcase
        end
      4'h7:
          casez (\$61 )
            1'h1:
                web_reg_next = web;
          endcase
    endcase
    casez (rst)
      1'h1:
          web_reg_next = 1'h1;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$8 ) begin end
    din_reg_next = din_reg;
    casez (state)
      4'h0:
          ;
      4'h1:
          ;
      4'h2:
          din_reg_next = din;
      4'h3:
        begin
          casez (\$65 )
            1'h1:
                din_reg_next = din;
          endcase
          casez (\$69 )
            1'h1:
                din_reg_next = din;
          endcase
        end
      4'h7:
          casez (\$71 )
            1'h1:
                din_reg_next = din;
          endcase
    endcase
    casez (rst)
      1'h1:
          din_reg_next = 128'h00000000000000000000000000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$8 ) begin end
    state_next = state;
    casez (state)
      4'h0:
          casez (\$73 )
            1'h1:
                state_next = 4'h2;
          endcase
      4'h1:
          casez (\$93 )
            1'h1:
                state_next = 4'h2;
          endcase
      4'h2:
          casez (\$95 )
            1'h1:
                state_next = 4'h3;
          endcase
      4'h3:
        begin
          casez (\$97 )
            1'h1:
                casez (\$99 )
                  1'h1:
                      casez (main_stall)
                        1'h1:
                            state_next = 4'h4;
                        default:
                            state_next = 4'h5;
                      endcase
                  default:
                      casez (main_stall)
                        1'h1:
                            state_next = 4'h6;
                        default:
                            state_next = 4'h7;
                      endcase
                endcase
          endcase
          casez (\$101 )
            1'h1:
                casez (\$103 )
                  1'h1:
                      casez (main_stall)
                        1'h1:
                            state_next = 4'h4;
                        default:
                            state_next = 4'h5;
                      endcase
                  default:
                      casez (main_stall)
                        1'h1:
                            state_next = 4'h6;
                        default:
                            state_next = 4'h7;
                      endcase
                endcase
          endcase
          casez (\$107 )
            1'h1:
                casez (csb)
                  1'h1:
                      state_next = 4'h2;
                  default:
                      casez (\$109 )
                        1'h1:
                            state_next = 4'h9;
                        default:
                            state_next = 4'h3;
                      endcase
                endcase
          endcase
          casez (\$113 )
            1'h1:
                casez (csb)
                  1'h1:
                      state_next = 4'h2;
                  default:
                      casez (\$115 )
                        1'h1:
                            state_next = 4'h9;
                        default:
                            state_next = 4'h3;
                      endcase
                endcase
          endcase
        end
      4'h6:
          casez (\$117 )
            1'h1:
                state_next = 4'h7;
          endcase
      4'h7:
          casez (\$119 )
            1'h1:
                casez (csb)
                  1'h1:
                      state_next = 4'h2;
                  default:
                      casez (\$121 )
                        1'h1:
                            state_next = 4'h9;
                        default:
                            state_next = 4'h3;
                      endcase
                endcase
          endcase
      4'h4:
          casez (\$123 )
            1'h1:
                state_next = 4'h5;
          endcase
      4'h5:
          casez (\$125 )
            1'h1:
                state_next = 4'h7;
          endcase
      4'h8:
          state_next = 4'h1;
      4'h9:
          state_next = 4'h3;
    endcase
    casez (flush)
      1'h1:
          casez (\$127 )
            1'h1:
                state_next = 4'h1;
            default:
                state_next = 4'h8;
          endcase
    endcase
    casez (rst)
      1'h1:
          state_next = 4'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$8 ) begin end
    way_next = way;
    casez (state)
      4'h0:
          ;
      4'h1:
          casez (\$139 )
            1'h1:
                way_next = \$142 [0];
          endcase
      4'h2:
          ;
      4'h3:
        begin
          casez (\$144 )
            1'h1:
                casez (\$146 )
                  1'h1:
                      way_next = 1'h0;
                  default:
                      way_next = 1'h0;
                endcase
          endcase
          casez (\$148 )
            1'h1:
                casez (\$150 )
                  1'h1:
                      way_next = 1'h1;
                  default:
                      way_next = 1'h1;
                endcase
          endcase
          casez (\$154 )
            1'h1:
                way_next = 1'h0;
          endcase
          casez (\$158 )
            1'h1:
                way_next = 1'h1;
          endcase
        end
    endcase
    casez (flush)
      1'h1:
          way_next = 1'h0;
    endcase
    casez (rst)
      1'h1:
          way_next = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$8 ) begin end
    stall = 1'h1;
    casez (state)
      4'h2:
          stall = 1'h0;
      4'h3:
        begin
          casez (\$162 )
            1'h1:
                stall = 1'h0;
          endcase
          casez (\$166 )
            1'h1:
                stall = 1'h0;
          endcase
        end
      4'h7:
          casez (\$168 )
            1'h1:
                stall = 1'h0;
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$8 ) begin end
    dout = 128'h00000000000000000000000000000000;
    casez (state)
      4'h2:
          ;
      4'h3:
        begin
          casez (\$172 )
            1'h1:
                dout = \$174 ;
          endcase
          casez (\$182 )
            1'h1:
                dout = \$184 ;
          endcase
        end
      4'h7:
          casez (\$190 )
            1'h1:
                dout = \$192 ;
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$8 ) begin end
    tag_write_csb0 = 1'h1;
    casez (state)
      4'h0:
          tag_write_csb0 = 1'h0;
      4'h1:
          casez (way)
            1'h0:
                casez (\$200 )
                  1'h1:
                      tag_write_csb0 = 1'h0;
                endcase
            1'h1:
                casez (\$204 )
                  1'h1:
                      tag_write_csb0 = 1'h0;
                endcase
          endcase
      4'h2:
          ;
      4'h3:
        begin
          casez (\$208 )
            1'h1:
                casez (\$210 )
                  1'h1:
                      tag_write_csb0 = 1'h0;
                endcase
          endcase
          casez (\$214 )
            1'h1:
                casez (\$216 )
                  1'h1:
                      tag_write_csb0 = 1'h0;
                endcase
          endcase
        end
      4'h6:
          ;
      4'h7:
          casez (\$218 )
            1'h1:
                casez (way)
                  1'h0:
                      tag_write_csb0 = 1'h0;
                  1'h1:
                      tag_write_csb0 = 1'h0;
                endcase
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$8 ) begin end
    tag_write_addr0 = 5'h00;
    casez (state)
      4'h0:
          tag_write_addr0 = set;
      4'h1:
          casez (way)
            1'h0:
                casez (\$222 )
                  1'h1:
                      tag_write_addr0 = set;
                endcase
            1'h1:
                casez (\$226 )
                  1'h1:
                      tag_write_addr0 = set;
                endcase
          endcase
      4'h2:
          ;
      4'h3:
        begin
          casez (\$230 )
            1'h1:
                casez (\$232 )
                  1'h1:
                      tag_write_addr0 = set;
                endcase
          endcase
          casez (\$236 )
            1'h1:
                casez (\$238 )
                  1'h1:
                      tag_write_addr0 = set;
                endcase
          endcase
        end
      4'h6:
          ;
      4'h7:
          casez (\$240 )
            1'h1:
                casez (way)
                  1'h0:
                      tag_write_addr0 = set;
                  1'h1:
                      tag_write_addr0 = set;
                endcase
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$8 ) begin end
    tag_write_din0 = 20'h00000;
    casez (state)
      4'h0:
          tag_write_din0 = 20'h00000;
      4'h1:
          casez (way)
            1'h0:
                casez (\$244 )
                  1'h1:
                    begin
                      tag_write_din0[19:10] = tag_read_dout0[19:10];
                      tag_write_din0[9:0] = { 2'h2, tag_read_dout0[7:0] };
                    end
                endcase
            1'h1:
                casez (\$248 )
                  1'h1:
                    begin
                      tag_write_din0[9:0] = tag_read_dout0[9:0];
                      tag_write_din0[19:10] = { 2'h2, tag_read_dout0[17:10] };
                    end
                endcase
          endcase
      4'h2:
          ;
      4'h3:
        begin
          casez (\$252 )
            1'h1:
                casez (\$254 )
                  1'h1:
                    begin
                      tag_write_din0[19:10] = tag_read_dout0[19:10];
                      tag_write_din0[9:0] = { 2'h3, tag };
                    end
                endcase
          endcase
          casez (\$258 )
            1'h1:
                casez (\$260 )
                  1'h1:
                    begin
                      tag_write_din0[9:0] = tag_read_dout0[9:0];
                      tag_write_din0[19:10] = { 2'h3, tag };
                    end
                endcase
          endcase
        end
      4'h6:
          ;
      4'h7:
          casez (\$262 )
            1'h1:
                casez (way)
                  1'h0:
                    begin
                      tag_write_din0[19:10] = tag_read_dout0[19:10];
                      tag_write_din0[9:0] = { 1'h1, \$264 , tag };
                    end
                  1'h1:
                    begin
                      tag_write_din0[9:0] = tag_read_dout0[9:0];
                      tag_write_din0[19:10] = { 1'h1, \$266 , tag };
                    end
                endcase
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$8 ) begin end
    data_write_csb0 = 1'h1;
    casez (state)
      4'h0:
          data_write_csb0 = 1'h0;
      4'h1:
          ;
      4'h2:
          ;
      4'h3:
          casez (\$270 )
            1'h1:
                casez (\$272 )
                  1'h1:
                      data_write_csb0 = 1'h0;
                endcase
          endcase
      4'h6:
          ;
      4'h7:
          casez (\$274 )
            1'h1:
                casez (way)
                  1'h0:
                      data_write_csb0 = 1'h0;
                endcase
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$8 ) begin end
    data_write_addr0 = 5'h00;
    casez (state)
      4'h0:
          data_write_addr0 = set;
      4'h1:
          ;
      4'h2:
          ;
      4'h3:
          casez (\$278 )
            1'h1:
                casez (\$280 )
                  1'h1:
                      data_write_addr0 = set;
                endcase
          endcase
      4'h6:
          ;
      4'h7:
          casez (\$282 )
            1'h1:
                casez (way)
                  1'h0:
                      data_write_addr0 = set;
                endcase
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$8 ) begin end
    data_write_din0 = 256'h0000000000000000000000000000000000000000000000000000000000000000;
    casez (state)
      4'h0:
          data_write_din0 = 256'h0000000000000000000000000000000000000000000000000000000000000000;
      4'h1:
          ;
      4'h2:
          ;
      4'h3:
          casez (\$286 )
            1'h1:
                casez (\$288 )
                  1'h1:
                    begin
                      data_write_din0 = data_read_dout0;
                      casez (offset)
                        1'h0:
                            data_write_din0[127:0] = din_reg;
                        1'h1:
                            data_write_din0[255:128] = din_reg;
                      endcase
                    end
                endcase
          endcase
      4'h6:
          ;
      4'h7:
          casez (\$290 )
            1'h1:
              begin
                casez (way)
                  1'h0:
                      data_write_din0 = main_dout;
                endcase
                casez (\$292 )
                  1'h1:
                      casez (way)
                        1'h0:
                            casez (offset)
                              1'h0:
                                  data_write_din0[127:0] = din_reg;
                              1'h1:
                                  data_write_din0[255:128] = din_reg;
                            endcase
                      endcase
                endcase
              end
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$8 ) begin end
    data_write_csb1 = 1'h1;
    casez (state)
      4'h0:
          data_write_csb1 = 1'h0;
      4'h1:
          ;
      4'h2:
          ;
      4'h3:
          casez (\$296 )
            1'h1:
                casez (\$298 )
                  1'h1:
                      data_write_csb1 = 1'h0;
                endcase
          endcase
      4'h6:
          ;
      4'h7:
          casez (\$300 )
            1'h1:
                casez (way)
                  1'h0:
                      ;
                  1'h1:
                      data_write_csb1 = 1'h0;
                endcase
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$8 ) begin end
    data_write_addr1 = 5'h00;
    casez (state)
      4'h0:
          data_write_addr1 = set;
      4'h1:
          ;
      4'h2:
          ;
      4'h3:
          casez (\$304 )
            1'h1:
                casez (\$306 )
                  1'h1:
                      data_write_addr1 = set;
                endcase
          endcase
      4'h6:
          ;
      4'h7:
          casez (\$308 )
            1'h1:
                casez (way)
                  1'h0:
                      ;
                  1'h1:
                      data_write_addr1 = set;
                endcase
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$8 ) begin end
    data_write_din1 = 256'h0000000000000000000000000000000000000000000000000000000000000000;
    casez (state)
      4'h0:
          data_write_din1 = 256'h0000000000000000000000000000000000000000000000000000000000000000;
      4'h1:
          ;
      4'h2:
          ;
      4'h3:
          casez (\$312 )
            1'h1:
                casez (\$314 )
                  1'h1:
                    begin
                      data_write_din1 = data_read_dout1;
                      casez (offset)
                        1'h0:
                            data_write_din1[127:0] = din_reg;
                        1'h1:
                            data_write_din1[255:128] = din_reg;
                      endcase
                    end
                endcase
          endcase
      4'h6:
          ;
      4'h7:
          casez (\$316 )
            1'h1:
              begin
                casez (way)
                  1'h0:
                      ;
                  1'h1:
                      data_write_din1 = main_dout;
                endcase
                casez (\$318 )
                  1'h1:
                      casez (way)
                        1'h0:
                            ;
                        1'h1:
                            casez (offset)
                              1'h0:
                                  data_write_din1[127:0] = din_reg;
                              1'h1:
                                  data_write_din1[255:128] = din_reg;
                            endcase
                      endcase
                endcase
              end
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$8 ) begin end
    tag_read_csb0 = 1'h0;
    casez (state)
      4'h0:
          ;
      4'h1:
        begin
          tag_read_csb0 = 1'h0;
          casez (way)
            1'h0:
                ;
            1'h1:
                casez (\$324 )
                  1'h1:
                      tag_read_csb0 = 1'h0;
                endcase
          endcase
        end
      4'h2:
          tag_read_csb0 = 1'h0;
      4'h3:
        begin
          tag_read_csb0 = 1'h0;
          casez (\$328 )
            1'h1:
                tag_read_csb0 = 1'h0;
          endcase
          casez (\$332 )
            1'h1:
                tag_read_csb0 = 1'h0;
          endcase
        end
      4'h6:
          tag_read_csb0 = 1'h0;
      4'h7:
        begin
          tag_read_csb0 = 1'h0;
          casez (\$334 )
            1'h1:
                tag_read_csb0 = 1'h0;
          endcase
        end
      4'h4:
          tag_read_csb0 = 1'h0;
      4'h5:
          tag_read_csb0 = 1'h0;
      4'h8:
          tag_read_csb0 = 1'h0;
      4'h9:
          tag_read_csb0 = 1'h0;
    endcase
    casez (flush)
      1'h1:
          tag_read_csb0 = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$8 ) begin end
    tag_read_addr0 = 5'h00;
    casez (state)
      4'h0:
          ;
      4'h1:
        begin
          tag_read_addr0 = set;
          casez (way)
            1'h0:
                ;
            1'h1:
                casez (\$340 )
                  1'h1:
                      tag_read_addr0 = \$343 [4:0];
                endcase
          endcase
        end
      4'h2:
          tag_read_addr0 = addr[5:1];
      4'h3:
        begin
          tag_read_addr0 = set;
          casez (\$347 )
            1'h1:
                tag_read_addr0 = addr[5:1];
          endcase
          casez (\$351 )
            1'h1:
                tag_read_addr0 = addr[5:1];
          endcase
        end
      4'h6:
          tag_read_addr0 = set;
      4'h7:
        begin
          tag_read_addr0 = set;
          casez (\$353 )
            1'h1:
                tag_read_addr0 = addr[5:1];
          endcase
        end
      4'h4:
          tag_read_addr0 = set;
      4'h5:
          tag_read_addr0 = set;
      4'h8:
          tag_read_addr0 = 5'h00;
      4'h9:
          tag_read_addr0 = set;
    endcase
    casez (flush)
      1'h1:
          tag_read_addr0 = 5'h00;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$8 ) begin end
    data_read_csb0 = 1'h0;
    casez (state)
      4'h0:
          ;
      4'h1:
        begin
          data_read_csb0 = 1'h0;
          casez (way)
            1'h0:
                ;
            1'h1:
                casez (\$359 )
                  1'h1:
                      data_read_csb0 = 1'h0;
                endcase
          endcase
        end
      4'h2:
          data_read_csb0 = 1'h0;
      4'h3:
        begin
          data_read_csb0 = 1'h0;
          casez (\$363 )
            1'h1:
                data_read_csb0 = 1'h0;
          endcase
          casez (\$367 )
            1'h1:
                data_read_csb0 = 1'h0;
          endcase
        end
      4'h6:
          data_read_csb0 = 1'h0;
      4'h7:
        begin
          data_read_csb0 = 1'h0;
          casez (\$369 )
            1'h1:
                data_read_csb0 = 1'h0;
          endcase
        end
      4'h4:
          data_read_csb0 = 1'h0;
      4'h5:
          data_read_csb0 = 1'h0;
      4'h8:
          data_read_csb0 = 1'h0;
      4'h9:
          data_read_csb0 = 1'h0;
    endcase
    casez (flush)
      1'h1:
          data_read_csb0 = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$8 ) begin end
    data_read_addr0 = 5'h00;
    casez (state)
      4'h0:
          ;
      4'h1:
        begin
          data_read_addr0 = set;
          casez (way)
            1'h0:
                ;
            1'h1:
                casez (\$375 )
                  1'h1:
                      data_read_addr0 = \$378 [4:0];
                endcase
          endcase
        end
      4'h2:
          data_read_addr0 = addr[5:1];
      4'h3:
        begin
          data_read_addr0 = set;
          casez (\$382 )
            1'h1:
                data_read_addr0 = addr[5:1];
          endcase
          casez (\$386 )
            1'h1:
                data_read_addr0 = addr[5:1];
          endcase
        end
      4'h6:
          data_read_addr0 = set;
      4'h7:
        begin
          data_read_addr0 = set;
          casez (\$388 )
            1'h1:
                data_read_addr0 = addr[5:1];
          endcase
        end
      4'h4:
          data_read_addr0 = set;
      4'h5:
          data_read_addr0 = set;
      4'h8:
          data_read_addr0 = 5'h00;
      4'h9:
          data_read_addr0 = set;
    endcase
    casez (flush)
      1'h1:
          data_read_addr0 = 5'h00;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$8 ) begin end
    data_read_csb1 = 1'h0;
    casez (state)
      4'h0:
          ;
      4'h1:
        begin
          data_read_csb1 = 1'h0;
          casez (way)
            1'h0:
                ;
            1'h1:
                casez (\$394 )
                  1'h1:
                      data_read_csb1 = 1'h0;
                endcase
          endcase
        end
      4'h2:
          data_read_csb1 = 1'h0;
      4'h3:
        begin
          data_read_csb1 = 1'h0;
          casez (\$398 )
            1'h1:
                data_read_csb1 = 1'h0;
          endcase
          casez (\$402 )
            1'h1:
                data_read_csb1 = 1'h0;
          endcase
        end
      4'h6:
          data_read_csb1 = 1'h0;
      4'h7:
        begin
          data_read_csb1 = 1'h0;
          casez (\$404 )
            1'h1:
                data_read_csb1 = 1'h0;
          endcase
        end
      4'h4:
          data_read_csb1 = 1'h0;
      4'h5:
          data_read_csb1 = 1'h0;
      4'h8:
          data_read_csb1 = 1'h0;
      4'h9:
          data_read_csb1 = 1'h0;
    endcase
    casez (flush)
      1'h1:
          data_read_csb1 = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$8 ) begin end
    data_read_addr1 = 5'h00;
    casez (state)
      4'h0:
          ;
      4'h1:
        begin
          data_read_addr1 = set;
          casez (way)
            1'h0:
                ;
            1'h1:
                casez (\$410 )
                  1'h1:
                      data_read_addr1 = \$413 [4:0];
                endcase
          endcase
        end
      4'h2:
          data_read_addr1 = addr[5:1];
      4'h3:
        begin
          data_read_addr1 = set;
          casez (\$417 )
            1'h1:
                data_read_addr1 = addr[5:1];
          endcase
          casez (\$421 )
            1'h1:
                data_read_addr1 = addr[5:1];
          endcase
        end
      4'h6:
          data_read_addr1 = set;
      4'h7:
        begin
          data_read_addr1 = set;
          casez (\$423 )
            1'h1:
                data_read_addr1 = addr[5:1];
          endcase
        end
      4'h4:
          data_read_addr1 = set;
      4'h5:
          data_read_addr1 = set;
      4'h8:
          data_read_addr1 = 5'h00;
      4'h9:
          data_read_addr1 = set;
    endcase
    casez (flush)
      1'h1:
          data_read_addr1 = 5'h00;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$8 ) begin end
    main_csb = 1'h1;
    casez (state)
      4'h0:
          ;
      4'h1:
          casez (way)
            1'h0:
                casez (\$427 )
                  1'h1:
                      main_csb = 1'h0;
                endcase
            1'h1:
                casez (\$431 )
                  1'h1:
                      main_csb = 1'h0;
                endcase
          endcase
      4'h2:
          ;
      4'h3:
        begin
          casez (\$433 )
            1'h1:
              begin
                casez (\$435 )
                  1'h1:
                      casez (\$437 )
                        1'h1:
                            main_csb = 1'h0;
                        default:
                            main_csb = 1'h0;
                      endcase
                endcase
                casez (\$439 )
                  1'h1:
                      casez (\$441 )
                        1'h1:
                            main_csb = 1'h0;
                        default:
                            main_csb = 1'h0;
                      endcase
                endcase
              end
          endcase
          casez (\$445 )
            1'h1:
                main_csb = 1'h1;
          endcase
          casez (\$449 )
            1'h1:
                main_csb = 1'h1;
          endcase
        end
      4'h6:
          casez (\$451 )
            1'h1:
                main_csb = 1'h0;
          endcase
      4'h7:
          ;
      4'h4:
          casez (\$453 )
            1'h1:
                casez (way)
                  1'h0:
                      main_csb = 1'h0;
                  1'h1:
                      main_csb = 1'h0;
                endcase
          endcase
      4'h5:
          casez (\$455 )
            1'h1:
                main_csb = 1'h0;
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$8 ) begin end
    main_web = 1'h1;
    casez (state)
      4'h0:
          ;
      4'h1:
          casez (way)
            1'h0:
                casez (\$459 )
                  1'h1:
                      main_web = 1'h0;
                endcase
            1'h1:
                casez (\$463 )
                  1'h1:
                      main_web = 1'h0;
                endcase
          endcase
      4'h2:
          ;
      4'h3:
          casez (\$465 )
            1'h1:
              begin
                casez (\$467 )
                  1'h1:
                      casez (\$469 )
                        1'h1:
                            main_web = 1'h0;
                        default:
                            main_web = 1'h1;
                      endcase
                endcase
                casez (\$471 )
                  1'h1:
                      casez (\$473 )
                        1'h1:
                            main_web = 1'h0;
                        default:
                            main_web = 1'h1;
                      endcase
                endcase
              end
          endcase
      4'h6:
          casez (\$475 )
            1'h1:
                main_web = 1'h1;
          endcase
      4'h7:
          ;
      4'h4:
          casez (\$477 )
            1'h1:
                casez (way)
                  1'h0:
                      main_web = 1'h0;
                  1'h1:
                      main_web = 1'h0;
                endcase
          endcase
      4'h5:
          casez (\$479 )
            1'h1:
                main_web = 1'h1;
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$8 ) begin end
    main_addr = 13'h0000;
    casez (state)
      4'h0:
          ;
      4'h1:
          casez (way)
            1'h0:
                casez (\$483 )
                  1'h1:
                      main_addr = { tag_read_dout0[7:0], set };
                endcase
            1'h1:
                casez (\$487 )
                  1'h1:
                      main_addr = { tag_read_dout0[17:10], set };
                endcase
          endcase
      4'h2:
          ;
      4'h3:
          casez (\$489 )
            1'h1:
              begin
                casez (\$491 )
                  1'h1:
                      casez (\$493 )
                        1'h1:
                            main_addr = { tag_read_dout0[7:0], set };
                        default:
                            main_addr = { tag, set };
                      endcase
                endcase
                casez (\$495 )
                  1'h1:
                      casez (\$497 )
                        1'h1:
                            main_addr = { tag_read_dout0[17:10], set };
                        default:
                            main_addr = { tag, set };
                      endcase
                endcase
              end
          endcase
      4'h6:
          casez (\$499 )
            1'h1:
                main_addr = { tag, set };
          endcase
      4'h7:
          ;
      4'h4:
          casez (\$501 )
            1'h1:
                casez (way)
                  1'h0:
                      main_addr = { \$503 , set };
                  1'h1:
                      main_addr = { \$507 , set };
                endcase
          endcase
      4'h5:
          casez (\$511 )
            1'h1:
                main_addr = { tag, set };
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$8 ) begin end
    main_din = 256'h0000000000000000000000000000000000000000000000000000000000000000;
    casez (state)
      4'h0:
          ;
      4'h1:
          casez (way)
            1'h0:
                casez (\$515 )
                  1'h1:
                      main_din = data_read_dout0;
                endcase
            1'h1:
                casez (\$519 )
                  1'h1:
                      main_din = data_read_dout1;
                endcase
          endcase
      4'h2:
          ;
      4'h3:
          casez (\$521 )
            1'h1:
              begin
                casez (\$523 )
                  1'h1:
                      casez (\$525 )
                        1'h1:
                            main_din = data_read_dout0;
                      endcase
                endcase
                casez (\$527 )
                  1'h1:
                      casez (\$529 )
                        1'h1:
                            main_din = data_read_dout1;
                      endcase
                endcase
              end
          endcase
      4'h6:
          ;
      4'h7:
          ;
      4'h4:
          casez (\$531 )
            1'h1:
                casez (way)
                  1'h0:
                      main_din = data_read_dout0;
                  1'h1:
                      main_din = data_read_dout1;
                endcase
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$8 ) begin end
    use_write_csb0 = 1'h1;
    casez (state)
      4'h0:
          use_write_csb0 = 1'h0;
      4'h1:
          ;
      4'h2:
          ;
      4'h3:
        begin
          casez (\$535 )
            1'h1:
                use_write_csb0 = 1'h0;
          endcase
          casez (\$539 )
            1'h1:
                use_write_csb0 = 1'h0;
          endcase
        end
      4'h6:
          ;
      4'h7:
          casez (\$541 )
            1'h1:
                use_write_csb0 = 1'h0;
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$8 ) begin end
    use_write_addr0 = 5'h00;
    casez (state)
      4'h0:
          use_write_addr0 = set;
      4'h1:
          ;
      4'h2:
          ;
      4'h3:
        begin
          casez (\$545 )
            1'h1:
                use_write_addr0 = set;
          endcase
          casez (\$549 )
            1'h1:
                use_write_addr0 = set;
          endcase
        end
      4'h6:
          ;
      4'h7:
          casez (\$551 )
            1'h1:
                use_write_addr0 = set;
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$8 ) begin end
    use_write_din0 = 2'h0;
    casez (state)
      4'h0:
          use_write_din0 = 2'h2;
      4'h1:
          ;
      4'h2:
          ;
      4'h3:
        begin
          casez (\$555 )
            1'h1:
              begin
                use_write_din0[1] = \$565 [0];
                use_write_din0[0] = 1'h1;
              end
          endcase
          casez (\$569 )
            1'h1:
              begin
                use_write_din0[0] = \$574 [0];
                use_write_din0[1] = 1'h1;
              end
          endcase
        end
      4'h6:
          ;
      4'h7:
          casez (\$581 )
            1'h1:
              begin
                use_write_din0[0] = \$588 [0];
                use_write_din0[1] = \$595 [0];
                casez (way)
                  1'h0:
                      use_write_din0[0] = 1'h1;
                  1'h1:
                      use_write_din0[1] = 1'h1;
                endcase
              end
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$8 ) begin end
    use_read_csb0 = 1'h0;
    casez (state)
      4'h0:
          ;
      4'h1:
          ;
      4'h2:
          use_read_csb0 = 1'h0;
      4'h3:
        begin
          use_read_csb0 = 1'h0;
          casez (\$599 )
            1'h1:
                use_read_csb0 = 1'h0;
          endcase
          casez (\$603 )
            1'h1:
                use_read_csb0 = 1'h0;
          endcase
        end
      4'h6:
          use_read_csb0 = 1'h0;
      4'h7:
        begin
          use_read_csb0 = 1'h0;
          casez (\$605 )
            1'h1:
                use_read_csb0 = 1'h0;
          endcase
        end
      4'h5:
          use_read_csb0 = 1'h0;
      4'h9:
          use_read_csb0 = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$8 ) begin end
    use_read_addr0 = 5'h00;
    casez (state)
      4'h0:
          ;
      4'h1:
          ;
      4'h2:
          use_read_addr0 = addr[5:1];
      4'h3:
        begin
          use_read_addr0 = set;
          casez (\$609 )
            1'h1:
                use_read_addr0 = addr[5:1];
          endcase
          casez (\$613 )
            1'h1:
                use_read_addr0 = addr[5:1];
          endcase
        end
      4'h6:
          use_read_addr0 = set;
      4'h7:
        begin
          use_read_addr0 = set;
          casez (\$615 )
            1'h1:
                use_read_addr0 = addr[5:1];
          endcase
        end
      4'h5:
          use_read_addr0 = set;
      4'h9:
          use_read_addr0 = set;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$8 ) begin end
    tag_next = tag;
    casez (state)
      4'h0:
          ;
      4'h1:
          ;
      4'h2:
          tag_next = addr[13:6];
      4'h3:
        begin
          casez (\$3 )
            1'h1:
                tag_next = addr[13:6];
          endcase
          casez (\$7 )
            1'h1:
                tag_next = addr[13:6];
          endcase
        end
      4'h7:
          casez (\$9 )
            1'h1:
                tag_next = addr[13:6];
          endcase
    endcase
    casez (rst)
      1'h1:
          tag_next = 8'h00;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$8 ) begin end
    set_next = set;
    casez (state)
      4'h0:
          set_next = \$12 [4:0];
      4'h1:
          casez (\$28 )
            1'h1:
                set_next = \$31 [4:0];
          endcase
      4'h2:
          set_next = addr[5:1];
      4'h3:
        begin
          casez (\$35 )
            1'h1:
                set_next = addr[5:1];
          endcase
          casez (\$39 )
            1'h1:
                set_next = addr[5:1];
          endcase
        end
      4'h7:
          casez (\$41 )
            1'h1:
                set_next = addr[5:1];
          endcase
    endcase
    casez (flush)
      1'h1:
          set_next = 5'h00;
    endcase
    casez (rst)
      1'h1:
          set_next = 5'h00;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$8 ) begin end
    offset_next = offset;
    casez (state)
      4'h0:
          ;
      4'h1:
          ;
      4'h2:
          offset_next = addr[0];
      4'h3:
        begin
          casez (\$45 )
            1'h1:
                offset_next = addr[0];
          endcase
          casez (\$49 )
            1'h1:
                offset_next = addr[0];
          endcase
        end
      4'h7:
          casez (\$51 )
            1'h1:
                offset_next = addr[0];
          endcase
    endcase
    casez (rst)
      1'h1:
          offset_next = 1'h0;
    endcase
  end
  assign \$11  = \$12 ;
  assign \$30  = \$31 ;
  assign \$141  = \$142 ;
  assign \$342  = \$343 ;
  assign \$377  = \$378 ;
  assign \$412  = \$413 ;
  assign \$557  = \$560 ;
  assign \$562  = \$565 ;
  assign \$571  = \$574 ;
  assign \$576  = \$579 ;
  assign \$583  = \$588 ;
  assign \$590  = \$595 ;
  assign \$26  = way;
  assign \$87  = way;
endmodule
