# Generated by build_srams.sh from l1d/sram_128x32_1r1w_config.py
word_size = 128
num_words = 32
num_rw_ports = 0
num_r_ports = 1
num_w_ports = 1
output_path = "/media/nisitha/My_Passport/MOODLE/OpenRAM_Project/OpenRAM_Memory_Design/cache/sram/sram_128x32_1r1w"
output_name = "sram_128x32_1r1w"

tech_name = "scn4m_subm"
nominal_corner_only = True
analytical_delay = True
check_lvsdrc = True
# Call magic/netgen directly; we already run inside the Nix devShell
use_nix = False
