/* Generated by Amaranth Yosys 0.35 (PyPI ver 0.35.0.0.post81, git sha1 cc31c6ebc) */




module l1d(main_web, main_addr, main_din, main_dout, main_stall, clk, rst, flush, csb, web, addr, din, dout, stall, main_csb);
  reg \$auto$verilog_backend.cc:2189:dump_module$7  = 0;
  wire \$1 ;
  wire \$10 ;
  wire \$101 ;
  wire [31:0] \$103 ;
  wire [2:0] \$104 ;
  wire [8:0] \$106 ;
  wire \$109 ;
  wire \$111 ;
  wire \$113 ;
  wire \$115 ;
  wire \$117 ;
  wire \$119 ;
  wire \$12 ;
  wire \$121 ;
  wire \$123 ;
  wire \$125 ;
  wire \$127 ;
  wire \$129 ;
  wire \$131 ;
  wire \$133 ;
  wire \$135 ;
  wire \$137 ;
  wire \$139 ;
  wire \$14 ;
  wire \$141 ;
  wire \$143 ;
  wire \$145 ;
  wire \$147 ;
  wire \$149 ;
  wire \$151 ;
  wire \$153 ;
  wire \$155 ;
  wire \$157 ;
  wire \$159 ;
  wire \$16 ;
  wire \$161 ;
  wire \$163 ;
  wire \$165 ;
  wire \$167 ;
  wire \$169 ;
  wire \$171 ;
  wire \$173 ;
  wire \$175 ;
  wire \$177 ;
  wire \$179 ;
  wire [5:0] \$18 ;
  wire \$181 ;
  wire \$183 ;
  wire \$185 ;
  wire \$187 ;
  wire \$189 ;
  wire [5:0] \$19 ;
  wire [5:0] \$191 ;
  wire [5:0] \$192 ;
  wire \$194 ;
  wire \$196 ;
  wire \$198 ;
  wire \$200 ;
  wire \$202 ;
  wire \$204 ;
  wire \$206 ;
  wire \$208 ;
  wire \$21 ;
  wire \$210 ;
  wire \$212 ;
  wire \$214 ;
  wire \$216 ;
  wire [5:0] \$218 ;
  wire [5:0] \$219 ;
  wire \$221 ;
  wire \$223 ;
  wire \$225 ;
  wire \$227 ;
  wire \$229 ;
  wire \$23 ;
  wire \$231 ;
  wire \$233 ;
  wire \$235 ;
  wire \$237 ;
  wire \$239 ;
  wire \$241 ;
  wire \$243 ;
  wire \$245 ;
  wire \$247 ;
  wire \$249 ;
  wire \$25 ;
  wire \$251 ;
  wire \$253 ;
  wire \$255 ;
  wire \$257 ;
  wire \$259 ;
  wire \$261 ;
  wire \$263 ;
  wire \$265 ;
  wire \$267 ;
  wire \$269 ;
  wire \$27 ;
  wire \$271 ;
  wire \$273 ;
  wire \$275 ;
  wire \$277 ;
  wire \$279 ;
  wire \$281 ;
  wire \$29 ;
  wire \$3 ;
  wire \$31 ;
  wire \$33 ;
  wire \$35 ;
  wire \$37 ;
  wire \$39 ;
  wire \$41 ;
  wire \$43 ;
  wire \$45 ;
  wire \$47 ;
  wire \$49 ;
  wire \$5 ;
  wire \$51 ;
  wire \$53 ;
  wire \$55 ;
  wire \$57 ;
  wire \$59 ;
  wire \$61 ;
  wire \$63 ;
  wire \$65 ;
  wire \$67 ;
  wire \$69 ;
  wire [5:0] \$7 ;
  wire \$71 ;
  wire \$73 ;
  wire \$75 ;
  wire \$77 ;
  wire \$79 ;
  wire [5:0] \$8 ;
  wire \$81 ;
  wire \$83 ;
  wire \$85 ;
  wire \$87 ;
  wire \$89 ;
  wire \$91 ;
  wire \$93 ;
  wire [31:0] \$95 ;
  wire [2:0] \$96 ;
  wire [8:0] \$98 ;
  input [15:0] addr;
  wire [15:0] addr;
  input clk;
  wire clk;
  input csb;
  wire csb;
  reg [4:0] data_read_addr0;
  reg data_read_csb0;
  wire [127:0] data_read_dout0;
  reg [4:0] data_write_addr0;
  reg data_write_csb0;
  reg [127:0] data_write_din0;
  input [31:0] din;
  wire [31:0] din;
  reg [31:0] din_reg = 32'd0;
  reg [31:0] din_reg_next;
  output [31:0] dout;
  reg [31:0] dout;
  input flush;
  wire flush;
  output [13:0] main_addr;
  reg [13:0] main_addr;
  output main_csb;
  reg main_csb;
  output [127:0] main_din;
  reg [127:0] main_din;
  input [127:0] main_dout;
  wire [127:0] main_dout;
  input main_stall;
  wire main_stall;
  output main_web;
  reg main_web;
  reg [1:0] offset = 2'h0;
  reg [1:0] offset_next;
  input rst;
  wire rst;
  reg [4:0] set = 5'h00;
  reg [4:0] set_next;
  output stall;
  reg stall;
  reg [3:0] state = 4'h0;
  reg [3:0] state_next;
  reg [8:0] tag = 9'h000;
  reg [8:0] tag_next;
  reg [4:0] tag_read_addr0;
  reg tag_read_csb0;
  wire [10:0] tag_read_dout0;
  reg [4:0] tag_write_addr0;
  reg tag_write_csb0;
  reg [10:0] tag_write_din0;
  input web;
  wire web;
  reg web_reg = 1'h0;
  reg web_reg_next;
  assign \$95  = data_read_dout0 >> \$98 ;
  assign \$101  = ~  main_stall;
  assign \$104  = 1'h0 +  offset;
  assign \$106  = \$104  *  6'h20;
  assign \$103  = main_dout >> \$106 ;
  assign \$10  = ~  tag_read_dout0[9];
  assign \$109  = ~  main_stall;
  assign \$111  = tag_read_dout0[9] &  \$109 ;
  assign \$113  = tag_read_dout0[8:0] ==  tag;
  assign \$115  = tag_read_dout0[10] &  \$113 ;
  assign \$117  = ~  web_reg;
  assign \$119  = ~  main_stall;
  assign \$121  = ~  main_stall;
  assign \$123  = tag_read_dout0[9] &  \$121 ;
  assign \$125  = tag_read_dout0[8:0] ==  tag;
  assign \$127  = tag_read_dout0[10] &  \$125 ;
  assign \$12  = ~  main_stall;
  assign \$129  = ~  web_reg;
  assign \$131  = ~  main_stall;
  assign \$133  = ~  main_stall;
  assign \$135  = tag_read_dout0[9] &  \$133 ;
  assign \$137  = tag_read_dout0[8:0] ==  tag;
  assign \$139  = tag_read_dout0[10] &  \$137 ;
  assign \$141  = ~  web_reg;
  assign \$143  = ~  main_stall;
  assign \$145  = ~  web_reg;
  assign \$147  = tag_read_dout0[8:0] ==  tag;
  assign \$14  = \$10  |  \$12 ;
  assign \$149  = tag_read_dout0[10] &  \$147 ;
  assign \$151  = ~  web_reg;
  assign \$153  = ~  main_stall;
  assign \$155  = tag_read_dout0[8:0] ==  tag;
  assign \$157  = tag_read_dout0[10] &  \$155 ;
  assign \$159  = ~  web_reg;
  assign \$161  = ~  main_stall;
  assign \$163  = tag_read_dout0[8:0] ==  tag;
  assign \$165  = tag_read_dout0[10] &  \$163 ;
  assign \$167  = ~  web_reg;
  assign \$169  = ~  main_stall;
  assign \$171  = ~  web_reg;
  assign \$173  = ~  tag_read_dout0[9];
  assign \$175  = ~  main_stall;
  assign \$177  = \$173  |  \$175 ;
  assign \$179  = tag_read_dout0[8:0] ==  tag;
  assign \$181  = tag_read_dout0[10] &  \$179 ;
  assign \$183  = ~  main_stall;
  assign \$185  = ~  tag_read_dout0[9];
  assign \$187  = ~  main_stall;
  assign \$189  = \$185  |  \$187 ;
  assign \$192  = set +  1'h1;
  assign \$194  = tag_read_dout0[8:0] ==  tag;
  assign \$196  = tag_read_dout0[10] &  \$194 ;
  assign \$198  = ~  main_stall;
  assign \$1  = tag_read_dout0[8:0] ==  tag;
  assign \$19  = set +  1'h1;
  assign \$200  = ~  tag_read_dout0[9];
  assign \$202  = ~  main_stall;
  assign \$204  = \$200  |  \$202 ;
  assign \$206  = tag_read_dout0[8:0] ==  tag;
  assign \$208  = tag_read_dout0[10] &  \$206 ;
  assign \$210  = ~  main_stall;
  assign \$212  = ~  tag_read_dout0[9];
  assign \$214  = ~  main_stall;
  assign \$216  = \$212  |  \$214 ;
  assign \$21  = tag_read_dout0[8:0] ==  tag;
  assign \$219  = set +  1'h1;
  assign \$221  = tag_read_dout0[8:0] ==  tag;
  assign \$223  = tag_read_dout0[10] &  \$221 ;
  assign \$225  = ~  main_stall;
  assign \$227  = ~  main_stall;
  assign \$229  = tag_read_dout0[9] &  \$227 ;
  assign \$231  = ~  main_stall;
  assign \$233  = tag_read_dout0[10] &  tag_read_dout0[9];
  assign \$235  = tag_read_dout0[8:0] ==  tag;
  assign \$237  = tag_read_dout0[10] &  \$235 ;
  assign \$23  = tag_read_dout0[10] &  \$21 ;
  assign \$239  = ~  main_stall;
  assign \$241  = ~  main_stall;
  assign \$243  = ~  main_stall;
  assign \$245  = ~  main_stall;
  assign \$247  = tag_read_dout0[9] &  \$245 ;
  assign \$249  = ~  main_stall;
  assign \$251  = tag_read_dout0[10] &  tag_read_dout0[9];
  assign \$253  = ~  main_stall;
  assign \$255  = ~  main_stall;
  assign \$257  = ~  main_stall;
  assign \$25  = ~  main_stall;
  assign \$259  = ~  main_stall;
  assign \$261  = tag_read_dout0[9] &  \$259 ;
  assign \$263  = ~  main_stall;
  assign \$265  = tag_read_dout0[10] &  tag_read_dout0[9];
  assign \$267  = ~  main_stall;
  assign \$269  = ~  main_stall;
  assign \$271  = ~  main_stall;
  assign \$273  = ~  main_stall;
  assign \$275  = tag_read_dout0[9] &  \$273 ;
  assign \$277  = ~  main_stall;
  assign \$27  = tag_read_dout0[8:0] ==  tag;
  assign \$279  = tag_read_dout0[10] &  tag_read_dout0[9];
  assign \$281  = ~  main_stall;
  assign \$29  = tag_read_dout0[10] &  \$27 ;
  assign \$31  = ~  main_stall;
  assign \$33  = tag_read_dout0[8:0] ==  tag;
  assign \$35  = tag_read_dout0[10] &  \$33 ;
  assign \$37  = ~  main_stall;
  assign \$3  = tag_read_dout0[10] &  \$1 ;
  assign \$39  = tag_read_dout0[8:0] ==  tag;
  assign \$41  = tag_read_dout0[10] &  \$39 ;
  assign \$43  = ~  main_stall;
  assign \$45  = set ==  5'h1f;
  assign \$47  = ~  tag_read_dout0[9];
  assign \$49  = ~  main_stall;
  assign \$51  = \$47  |  \$49 ;
  assign \$55  = set ==  5'h1f;
  assign \$57  = \$53  &  \$55 ;
  assign \$5  = ~  main_stall;
  assign \$59  = ~  csb;
  assign \$61  = tag_read_dout0[10] &  tag_read_dout0[9];
  assign \$63  = tag_read_dout0[8:0] ==  tag;
  assign \$65  = tag_read_dout0[10] &  \$63 ;
  assign \$67  = ~  web_reg;
  assign \$69  = set ==  addr[6:2];
  assign \$71  = \$67  &  \$69 ;
  assign \$73  = ~  main_stall;
  assign \$75  = ~  main_stall;
  assign \$77  = set ==  addr[6:2];
  assign \$79  = ~  main_stall;
  assign \$81  = ~  main_stall;
  assign \$83  = |  set;
  assign \$85  = tag_read_dout0[8:0] ==  tag;
  assign \$87  = tag_read_dout0[10] &  \$85 ;
  assign \$8  = set +  1'h1;
  assign \$89  = ~  main_stall;
  assign \$91  = tag_read_dout0[8:0] ==  tag;
  assign \$93  = tag_read_dout0[10] &  \$91 ;
  assign \$96  = 1'h0 +  offset;
  assign \$98  = \$96  *  6'h20;
  always @(posedge clk)
    state <= state_next;
  always @(posedge clk)
    din_reg <= din_reg_next;
  always @(posedge clk)
    web_reg <= web_reg_next;
  always @(posedge clk)
    offset <= offset_next;
  always @(posedge clk)
    set <= set_next;
  always @(posedge clk)
    tag <= tag_next;
  l1d_tag_array \U$$0  (
    .addr0(tag_write_addr0),
    .addr1(tag_read_addr0),
    .clk0(clk),
    .clk1(clk),
    .csb0(tag_write_csb0),
    .csb1(tag_read_csb0),
    .din0(tag_write_din0),
    .dout1(tag_read_dout0)
  );
  sram_128x32_1r1w \U$$1  (
    .addr0(data_write_addr0),
    .addr1(data_read_addr0),
    .clk0(clk),
    .clk1(clk),
    .csb0(data_write_csb0),
    .csb1(data_read_csb0),
    .din0(data_write_din0),
    .dout1(data_read_dout0)
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$7 ) begin end
    din_reg_next = din_reg;
    casez (state)
      4'h0:
          ;
      4'h1:
          ;
      4'h2:
          din_reg_next = din;
      4'h3:
          casez (\$41 )
            1'h1:
                din_reg_next = din;
          endcase
      4'h7:
          casez (\$43 )
            1'h1:
                din_reg_next = din;
          endcase
    endcase
    casez (rst)
      1'h1:
          din_reg_next = 32'd0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$7 ) begin end
    state_next = state;
    casez (state)
      4'h0:
          casez (\$45 )
            1'h1:
                state_next = 4'h2;
          endcase
      4'h1:
          casez (\$57 )
            1'h1:
                state_next = 4'h2;
          endcase
      4'h2:
          casez (\$59 )
            1'h1:
                state_next = 4'h3;
          endcase
      4'h3:
        begin
          casez (\$61 )
            1'h1:
                casez (main_stall)
                  1'h1:
                      state_next = 4'h4;
                  default:
                      state_next = 4'h5;
                endcase
            default:
                casez (main_stall)
                  1'h1:
                      state_next = 4'h6;
                  default:
                      state_next = 4'h7;
                endcase
          endcase
          casez (\$65 )
            1'h1:
                casez (csb)
                  1'h1:
                      state_next = 4'h2;
                  default:
                      casez (\$71 )
                        1'h1:
                            state_next = 4'h9;
                        default:
                            state_next = 4'h3;
                      endcase
                endcase
          endcase
        end
      4'h6:
          casez (\$73 )
            1'h1:
                state_next = 4'h7;
          endcase
      4'h7:
          casez (\$75 )
            1'h1:
                casez (csb)
                  1'h1:
                      state_next = 4'h2;
                  default:
                      casez (\$77 )
                        1'h1:
                            state_next = 4'h9;
                        default:
                            state_next = 4'h3;
                      endcase
                endcase
          endcase
      4'h4:
          casez (\$79 )
            1'h1:
                state_next = 4'h5;
          endcase
      4'h5:
          casez (\$81 )
            1'h1:
                state_next = 4'h7;
          endcase
      4'h8:
          state_next = 4'h1;
      4'h9:
          state_next = 4'h3;
    endcase
    casez (flush)
      1'h1:
          casez (\$83 )
            1'h1:
                state_next = 4'h1;
            default:
                state_next = 4'h8;
          endcase
    endcase
    casez (rst)
      1'h1:
          state_next = 4'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$7 ) begin end
    stall = 1'h1;
    casez (state)
      4'h2:
          stall = 1'h0;
      4'h3:
          casez (\$87 )
            1'h1:
                stall = 1'h0;
          endcase
      4'h7:
          casez (\$89 )
            1'h1:
                stall = 1'h0;
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$7 ) begin end
    dout = 32'd0;
    casez (state)
      4'h2:
          ;
      4'h3:
          casez (\$93 )
            1'h1:
                dout = \$95 ;
          endcase
      4'h7:
          casez (\$101 )
            1'h1:
                dout = \$103 ;
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$7 ) begin end
    tag_write_csb0 = 1'h1;
    casez (state)
      4'h0:
          tag_write_csb0 = 1'h0;
      4'h1:
          casez (\$111 )
            1'h1:
                tag_write_csb0 = 1'h0;
          endcase
      4'h2:
          ;
      4'h3:
          casez (\$115 )
            1'h1:
                casez (\$117 )
                  1'h1:
                      tag_write_csb0 = 1'h0;
                endcase
          endcase
      4'h6:
          ;
      4'h7:
          casez (\$119 )
            1'h1:
                tag_write_csb0 = 1'h0;
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$7 ) begin end
    tag_write_addr0 = 5'h00;
    casez (state)
      4'h0:
          tag_write_addr0 = set;
      4'h1:
          casez (\$123 )
            1'h1:
                tag_write_addr0 = set;
          endcase
      4'h2:
          ;
      4'h3:
          casez (\$127 )
            1'h1:
                casez (\$129 )
                  1'h1:
                      tag_write_addr0 = set;
                endcase
          endcase
      4'h6:
          ;
      4'h7:
          casez (\$131 )
            1'h1:
                tag_write_addr0 = set;
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$7 ) begin end
    tag_write_din0 = 11'h000;
    casez (state)
      4'h0:
          tag_write_din0 = 11'h000;
      4'h1:
          casez (\$135 )
            1'h1:
                tag_write_din0 = { 2'h2, tag_read_dout0[8:0] };
          endcase
      4'h2:
          ;
      4'h3:
          casez (\$139 )
            1'h1:
                casez (\$141 )
                  1'h1:
                      tag_write_din0 = { 2'h3, tag };
                endcase
          endcase
      4'h6:
          ;
      4'h7:
          casez (\$143 )
            1'h1:
                tag_write_din0 = { 1'h1, \$145 , tag };
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$7 ) begin end
    data_write_csb0 = 1'h1;
    casez (state)
      4'h0:
          data_write_csb0 = 1'h0;
      4'h1:
          ;
      4'h2:
          ;
      4'h3:
          casez (\$149 )
            1'h1:
                casez (\$151 )
                  1'h1:
                      data_write_csb0 = 1'h0;
                endcase
          endcase
      4'h6:
          ;
      4'h7:
          casez (\$153 )
            1'h1:
                data_write_csb0 = 1'h0;
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$7 ) begin end
    data_write_addr0 = 5'h00;
    casez (state)
      4'h0:
          data_write_addr0 = set;
      4'h1:
          ;
      4'h2:
          ;
      4'h3:
          casez (\$157 )
            1'h1:
                casez (\$159 )
                  1'h1:
                      data_write_addr0 = set;
                endcase
          endcase
      4'h6:
          ;
      4'h7:
          casez (\$161 )
            1'h1:
                data_write_addr0 = set;
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$7 ) begin end
    data_write_din0 = 128'h00000000000000000000000000000000;
    casez (state)
      4'h0:
          data_write_din0 = 128'h00000000000000000000000000000000;
      4'h1:
          ;
      4'h2:
          ;
      4'h3:
          casez (\$165 )
            1'h1:
                casez (\$167 )
                  1'h1:
                    begin
                      data_write_din0 = data_read_dout0;
                      casez (offset)
                        2'h0:
                            data_write_din0[31:0] = din_reg;
                        2'h1:
                            data_write_din0[63:32] = din_reg;
                        2'h2:
                            data_write_din0[95:64] = din_reg;
                        2'h3:
                            data_write_din0[127:96] = din_reg;
                      endcase
                    end
                endcase
          endcase
      4'h6:
          ;
      4'h7:
          casez (\$169 )
            1'h1:
              begin
                data_write_din0 = main_dout;
                casez (\$171 )
                  1'h1:
                      casez (offset)
                        2'h0:
                            data_write_din0[31:0] = din_reg;
                        2'h1:
                            data_write_din0[63:32] = din_reg;
                        2'h2:
                            data_write_din0[95:64] = din_reg;
                        2'h3:
                            data_write_din0[127:96] = din_reg;
                      endcase
                endcase
              end
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$7 ) begin end
    tag_read_csb0 = 1'h0;
    casez (state)
      4'h0:
          ;
      4'h1:
        begin
          tag_read_csb0 = 1'h0;
          casez (\$177 )
            1'h1:
                tag_read_csb0 = 1'h0;
          endcase
        end
      4'h2:
          tag_read_csb0 = 1'h0;
      4'h3:
        begin
          tag_read_csb0 = 1'h0;
          casez (\$181 )
            1'h1:
                tag_read_csb0 = 1'h0;
          endcase
        end
      4'h6:
          tag_read_csb0 = 1'h0;
      4'h7:
        begin
          tag_read_csb0 = 1'h0;
          casez (\$183 )
            1'h1:
                tag_read_csb0 = 1'h0;
          endcase
        end
      4'h4:
          tag_read_csb0 = 1'h0;
      4'h5:
          tag_read_csb0 = 1'h0;
      4'h8:
          tag_read_csb0 = 1'h0;
      4'h9:
          tag_read_csb0 = 1'h0;
    endcase
    casez (flush)
      1'h1:
          tag_read_csb0 = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$7 ) begin end
    tag_read_addr0 = 5'h00;
    casez (state)
      4'h0:
          ;
      4'h1:
        begin
          tag_read_addr0 = set;
          casez (\$189 )
            1'h1:
                tag_read_addr0 = \$192 [4:0];
          endcase
        end
      4'h2:
          tag_read_addr0 = addr[6:2];
      4'h3:
        begin
          tag_read_addr0 = set;
          casez (\$196 )
            1'h1:
                tag_read_addr0 = addr[6:2];
          endcase
        end
      4'h6:
          tag_read_addr0 = set;
      4'h7:
        begin
          tag_read_addr0 = set;
          casez (\$198 )
            1'h1:
                tag_read_addr0 = addr[6:2];
          endcase
        end
      4'h4:
          tag_read_addr0 = set;
      4'h5:
          tag_read_addr0 = set;
      4'h8:
          tag_read_addr0 = 5'h00;
      4'h9:
          tag_read_addr0 = set;
    endcase
    casez (flush)
      1'h1:
          tag_read_addr0 = 5'h00;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$7 ) begin end
    data_read_csb0 = 1'h0;
    casez (state)
      4'h0:
          ;
      4'h1:
        begin
          data_read_csb0 = 1'h0;
          casez (\$204 )
            1'h1:
                data_read_csb0 = 1'h0;
          endcase
        end
      4'h2:
          data_read_csb0 = 1'h0;
      4'h3:
        begin
          data_read_csb0 = 1'h0;
          casez (\$208 )
            1'h1:
                data_read_csb0 = 1'h0;
          endcase
        end
      4'h6:
          data_read_csb0 = 1'h0;
      4'h7:
        begin
          data_read_csb0 = 1'h0;
          casez (\$210 )
            1'h1:
                data_read_csb0 = 1'h0;
          endcase
        end
      4'h4:
          data_read_csb0 = 1'h0;
      4'h5:
          data_read_csb0 = 1'h0;
      4'h8:
          data_read_csb0 = 1'h0;
      4'h9:
          data_read_csb0 = 1'h0;
    endcase
    casez (flush)
      1'h1:
          data_read_csb0 = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$7 ) begin end
    data_read_addr0 = 5'h00;
    casez (state)
      4'h0:
          ;
      4'h1:
        begin
          data_read_addr0 = set;
          casez (\$216 )
            1'h1:
                data_read_addr0 = \$219 [4:0];
          endcase
        end
      4'h2:
          data_read_addr0 = addr[6:2];
      4'h3:
        begin
          data_read_addr0 = set;
          casez (\$223 )
            1'h1:
                data_read_addr0 = addr[6:2];
          endcase
        end
      4'h6:
          data_read_addr0 = set;
      4'h7:
        begin
          data_read_addr0 = set;
          casez (\$225 )
            1'h1:
                data_read_addr0 = addr[6:2];
          endcase
        end
      4'h4:
          data_read_addr0 = set;
      4'h5:
          data_read_addr0 = set;
      4'h8:
          data_read_addr0 = 5'h00;
      4'h9:
          data_read_addr0 = set;
    endcase
    casez (flush)
      1'h1:
          data_read_addr0 = 5'h00;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$7 ) begin end
    main_csb = 1'h1;
    casez (state)
      4'h0:
          ;
      4'h1:
          casez (\$229 )
            1'h1:
                main_csb = 1'h0;
          endcase
      4'h2:
          ;
      4'h3:
        begin
          casez (\$231 )
            1'h1:
                casez (\$233 )
                  1'h1:
                      main_csb = 1'h0;
                  default:
                      main_csb = 1'h0;
                endcase
          endcase
          casez (\$237 )
            1'h1:
                main_csb = 1'h1;
          endcase
        end
      4'h6:
          casez (\$239 )
            1'h1:
                main_csb = 1'h0;
          endcase
      4'h7:
          ;
      4'h4:
          casez (\$241 )
            1'h1:
                main_csb = 1'h0;
          endcase
      4'h5:
          casez (\$243 )
            1'h1:
                main_csb = 1'h0;
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$7 ) begin end
    main_web = 1'h1;
    casez (state)
      4'h0:
          ;
      4'h1:
          casez (\$247 )
            1'h1:
                main_web = 1'h0;
          endcase
      4'h2:
          ;
      4'h3:
          casez (\$249 )
            1'h1:
                casez (\$251 )
                  1'h1:
                      main_web = 1'h0;
                  default:
                      main_web = 1'h1;
                endcase
          endcase
      4'h6:
          casez (\$253 )
            1'h1:
                main_web = 1'h1;
          endcase
      4'h7:
          ;
      4'h4:
          casez (\$255 )
            1'h1:
                main_web = 1'h0;
          endcase
      4'h5:
          casez (\$257 )
            1'h1:
                main_web = 1'h1;
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$7 ) begin end
    main_addr = 14'h0000;
    casez (state)
      4'h0:
          ;
      4'h1:
          casez (\$261 )
            1'h1:
                main_addr = { tag_read_dout0[8:0], set };
          endcase
      4'h2:
          ;
      4'h3:
          casez (\$263 )
            1'h1:
                casez (\$265 )
                  1'h1:
                      main_addr = { tag_read_dout0[8:0], set };
                  default:
                      main_addr = { tag, set };
                endcase
          endcase
      4'h6:
          casez (\$267 )
            1'h1:
                main_addr = { tag, set };
          endcase
      4'h7:
          ;
      4'h4:
          casez (\$269 )
            1'h1:
                main_addr = { tag_read_dout0[8:0], set };
          endcase
      4'h5:
          casez (\$271 )
            1'h1:
                main_addr = { tag, set };
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$7 ) begin end
    main_din = 128'h00000000000000000000000000000000;
    casez (state)
      4'h0:
          ;
      4'h1:
          casez (\$275 )
            1'h1:
                main_din = data_read_dout0;
          endcase
      4'h2:
          ;
      4'h3:
          casez (\$277 )
            1'h1:
                casez (\$279 )
                  1'h1:
                      main_din = data_read_dout0;
                endcase
          endcase
      4'h6:
          ;
      4'h7:
          ;
      4'h4:
          casez (\$281 )
            1'h1:
                main_din = data_read_dout0;
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$7 ) begin end
    tag_next = tag;
    casez (state)
      4'h0:
          ;
      4'h1:
          ;
      4'h2:
          tag_next = addr[15:7];
      4'h3:
          casez (\$3 )
            1'h1:
                tag_next = addr[15:7];
          endcase
      4'h7:
          casez (\$5 )
            1'h1:
                tag_next = addr[15:7];
          endcase
    endcase
    casez (rst)
      1'h1:
          tag_next = 9'h000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$7 ) begin end
    set_next = set;
    casez (state)
      4'h0:
          set_next = \$8 [4:0];
      4'h1:
          casez (\$16 )
            1'h1:
                set_next = \$19 [4:0];
          endcase
      4'h2:
          set_next = addr[6:2];
      4'h3:
          casez (\$23 )
            1'h1:
                set_next = addr[6:2];
          endcase
      4'h7:
          casez (\$25 )
            1'h1:
                set_next = addr[6:2];
          endcase
    endcase
    casez (flush)
      1'h1:
          set_next = 5'h00;
    endcase
    casez (rst)
      1'h1:
          set_next = 5'h00;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$7 ) begin end
    offset_next = offset;
    casez (state)
      4'h0:
          ;
      4'h1:
          ;
      4'h2:
          offset_next = addr[1:0];
      4'h3:
          casez (\$29 )
            1'h1:
                offset_next = addr[1:0];
          endcase
      4'h7:
          casez (\$31 )
            1'h1:
                offset_next = addr[1:0];
          endcase
    endcase
    casez (rst)
      1'h1:
          offset_next = 2'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$7 ) begin end
    web_reg_next = web_reg;
    casez (state)
      4'h0:
          ;
      4'h1:
          ;
      4'h2:
          web_reg_next = web;
      4'h3:
          casez (\$35 )
            1'h1:
                web_reg_next = web;
          endcase
      4'h7:
          casez (\$37 )
            1'h1:
                web_reg_next = web;
          endcase
    endcase
    casez (rst)
      1'h1:
          web_reg_next = 1'h1;
    endcase
  end
  assign \$7  = \$8 ;
  assign \$18  = \$19 ;
  assign \$191  = \$192 ;
  assign \$218  = \$219 ;
  assign \$16  = \$14 ;
  assign \$53  = \$51 ;
endmodule
